CREATE TABLE USER_TABLE (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(300) NOT NULL
);

CREATE TABLE CATEGORY (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(20 CHAR) NOT NULL
);

CREATE TABLE QUESTION (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question      VARCHAR2(300 CHAR) NOT NULL,
    add_date      DATE DEFAULT SYSDATE,
    category_id   NUMBER,
    tts_key       VARCHAR2(50 CHAR),
    
    CONSTRAINT fk_question_userid FOREIGN KEY (category_id) REFERENCES CATEGORY(id) ON DELETE SET NULL
);

CREATE TABLE ANSWER (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL,
    question_id   NUMBER NOT NULL,
    answer        VARCHAR2(1000 CHAR),
    
    CONSTRAINT fk_answer_userid FOREIGN KEY (user_id) REFERENCES USER_TABLE(id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_questionid FOREIGN KEY (question_id) REFERENCES QUESTION(id) ON DELETE CASCADE
);

---------------------------------------------------------------------------------------------------------

INSERT INTO user_table(username, password_hash) VALUES('이은상', '$2a$12$M.Ha8YZQop1KiSnW.9/4RO/IpfpYpLrpWGv2teChe8U9s8ZJi6SRK');
INSERT INTO user_table(username, password_hash) VALUES('이세중', '$2a$12$M.Ha8YZQop1KiSnW.9/4RO/IpfpYpLrpWGv2teChe8U9s8ZJi6SRK');
INSERT INTO user_table(username, password_hash) VALUES('신효경', '$2a$12$M.Ha8YZQop1KiSnW.9/4RO/IpfpYpLrpWGv2teChe8U9s8ZJi6SRK');

INSERT INTO category(name) VALUES('네트워크');
INSERT INTO category(name) VALUES('운영체제');
INSERT INTO category(name) VALUES('데이터베이스');
INSERT INTO category(name) VALUES('알고리즘');
INSERT INTO category(name) VALUES('보안');
INSERT INTO category(name) VALUES('Java');
INSERT INTO category(name) VALUES('Spring');
INSERT INTO category(name) VALUES('JPA');
INSERT INTO category(name) VALUES('프로젝트');

-- QUESTION 데이터: CATEGORY의 마지막 값('프로젝트') 이후에 이어지는 INSERT 문
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (1,'웹 통신의 큰 흐름: https://www.google.com/ 을 접속할 때 일어나는 일',to_date('2026-02-09','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (2,'프로세스와 스레드의 차이를 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (3,'데이터베이스에서 인덱스를 사용하는 이유 및 장단점에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (4,'JVM의 구조와 Java의 실행방식을 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (5,'GC가 무엇인지, 필요한 이유는 무엇인지, 동작방식에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (6,'컬렉션 프레임워크에 대해서 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (7,'제네릭에 대해서 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (8,'어노테이션에 대해서 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (9,'오버라이딩과 오버로딩이 무엇이며 어떤 차이가 있을까요?',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (10,'[꼬리질문] DNS의 개념과 도메인 주소를 ip로 변환하는 과정을 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (11,'[꼬리질문] TLS가 무엇인지 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (12,'[꼬리질문] ARP가 무엇인지 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (13,'[꼬리질문] OSI 7계층에서 1계층부터 7계층까지의 역직렬화에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (14,'[꼬리질문] 프로세스와 스레드에서 코드, 데이터, 힙, 스택, 레지스터에 각각 저장되는 데이터는 무엇인가요?',to_date('2026-02-09','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (15,'[꼬리질문] 스레드 중 하나가 죽으면 프로세스 전체가 죽을 수 있는 이유는 무엇인가요?',to_date('2026-02-09','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (16,'[꼬리질문] 병목현상에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (17,'[꼬리질문] 레이스컨디션에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (18,'[꼬리질문] IPC에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (19,'[꼬리질문] DB의 테이블에서 선택도가 높은 컬럼의 의미와 예시를 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (20,'[꼬리질문] DB에서 옵티마이저가 무엇인지 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (21,'[꼬리질문] Java의 JNI에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (22,'[꼬리질문] JVM의 메모리 영역 중 스택, 메서드, 힙 영역에 각각 어떤 데이터가 저장되나요?',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (23,'[꼬리질문] 가비지 콜렉션에서 각 영역 및 영역 간 이동에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (24,'[꼬리질문] Minor GC와 Major GC에 대해 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (25,'[꼬리질문] GC Root가 무엇인지 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (26,'[꼬리질문] 인터페이스 구현체의 개념과 사용 예시를 들어주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (27,'[꼬리질문] 공변반환 타입이 무엇인지 설명해주세요.',to_date('2026-02-09','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (28,'배열과 링크드 리스트의 차이를 설명해주세요.',to_date('2026-02-12','YYYY-MM-DD'),4,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (29,'비대칭키 암호화, 대칭키 암호화에 대해 간단히 설명해주세요.',to_date('2026-02-12','YYYY-MM-DD'),5,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (30,'Spring DI/IoC는 어떻게 동작하나요?',to_date('2026-02-12','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (31,'인터페이스와 추상클래스의 차이점에 대해 설명해주세요.',to_date('2026-02-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (32,'클래스는 무엇이고 객체는 무엇인가요?',to_date('2026-02-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (33,'static 이란 무엇인가요?',to_date('2026-02-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (34,'자바의 원시타입들은 무엇이 있으며 각각 몇 바이트를 차지하나요?',to_date('2026-02-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (35,'접근 제어자의 종류와 이에 대해 설명해주세요.',to_date('2026-02-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (36,'객체지향 개념과 4대 특징에 대해서 설명해주세요.',to_date('2026-02-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (37,'[꼬리질문] DI가 객체 간 결합도를 낮출 수 있는 이유를 설명해주세요.',to_date('2026-02-12','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (38,'[꼬리질문] Java에서 static 멤버가 프로그램 종료까지 메모리에 남아있는 이유를 설명해주세요.',to_date('2026-02-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (39,'JPA 영속성 컨텍스트의 이점(5가지)을 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),8,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (40,'TCP와 UDP의 차이점에 대해서 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (41,'컨텍스트 스위칭에 대해 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (42,'객체지향 5대원칙에 대해서 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (43,'동일성와 동등성에 대해 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (44,'원시타입과 참조타입의 차이에 대해 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (45,'String, StringBuilder, StringBuffer 각각의 차이에 대해 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (46,'Checked Exception과 Unchecked Exception에 대해 설명해주세요. 그리고 스프링 트랜잭션 추상화에서 rollback 대상은 무엇인지 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (47,'Java 8에서 추가된 기능에 대해서 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (48,'[꼬리질문] TCP에서 시퀀스와 ACK가 무엇인가요?',to_date('2026-02-19','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (49,'[꼬리질문] PCB가 무엇인지 설명해주세요.',to_date('2026-02-19','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (50,'트랜잭션에 대해서 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (51,'List와 Set의 차이에 대해서 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),4,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (52,'단방향 암호화에 대해서 간단히 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),5,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (53,'try-with-resources에 대해서 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (54,'강한 결합과 느슨한 결합이 무엇인지 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (55,'자바의 직렬화와 역직렬화에 대해서 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (56,'자바의 동시성 이슈에 대해 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (57,'Mutable 객체와 Immutable 객체의 차이점에 대해 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (58,'자바에서 null을 안전하게 다루는 방법에 대해 설명해주세요.',to_date('2026-02-26','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (59,'Spring Bean이란 무엇인가요?',to_date('2026-03-02','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (60,'스프링 Bean의 생성 과정을 설명해주세요.',to_date('2026-03-02','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (61,'스프링 Bean의 Scope에 대해서 설명해주세요.',to_date('2026-03-02','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (62,'IoC 컨테이너의 역할은 무엇이 있을까요?',to_date('2026-03-02','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (63,'JPA Propagation 전파단계를 설명해주세요.',to_date('2026-03-02','YYYY-MM-DD'),8,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (64,'TCP 3, 4 way handshake에 대해서 설명해주세요.',to_date('2026-03-02','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (65,'JDK와 JRE의 차이점을 설명해주세요.',to_date('2026-03-02','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (66,'[프로젝트] Access Token과 Refresh Token을 나누어서 사용하는 이유?',to_date('2026-03-02','YYYY-MM-DD'),9,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (67,'[프로젝트] 왜 HTTP가 아니라 WebSocket을 사용했나요?',to_date('2026-03-02','YYYY-MM-DD'),9,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (68,'[꼬리질문] 웹소켓 말고 다른 실시간 통신 방식은 없나요?',to_date('2026-03-02','YYYY-MM-DD'),9,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (69,'DI 종류는 어떤것이 있고, 이들의 차이는 무엇인가요?',to_date('2026-03-05','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (70,'Autowiring 과정에 대해서 설명해주세요.',to_date('2026-03-05','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (71,'Spring Web MVC의 Dispatcher Servlet의 동작 원리에 대해서 간단히 설명해주세요.',to_date('2026-03-05','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (72,'동기와 비동기의 차이점과 장단점에 대해 설명해주세요.',to_date('2026-03-05','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (73,'ACID에 대해서 설명해주세요.',to_date('2026-03-05','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (74,'final keyword란 무엇인가요?(개념, 특징)',to_date('2026-03-05','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (75,'Wrapper class란 무엇이며 왜 사용하나요?',to_date('2026-03-05','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (76,'[프로젝트] 액세스 토큰은 왜 httpOnly 쿠키에 저장 안 했나요?',to_date('2026-03-05','YYYY-MM-DD'),9,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (77,'[프로젝트] 왜 WebSocket뿐만 아니라 STOMP를 사용했나요?',to_date('2026-03-05','YYYY-MM-DD'),9,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (78,'프론트 컨트롤러 패턴이란 무엇인가요?',to_date('2026-03-12','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (79,'Servlet Filter와 Spring Interceptor의 차이는 무엇인가요?',to_date('2026-03-12','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (80,'Spring에서 CORS 에러를 해결하기 위한 방법을 설명해주세요.',to_date('2026-03-12','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (81,'POJO란 무엇인가요? Spring Framework에서 POJO는 무엇이 될 수 있을까요?',to_date('2026-03-12','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (82,'Hash Function, HashTable에 대해서 설명해주세요.',to_date('2026-03-12','YYYY-MM-DD'),4,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (83,'JWT에 대해서 간단히 설명해주세요.',to_date('2026-03-12','YYYY-MM-DD'),5,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (84,'JPA를 쓴다면 그 이유에 대해서 설명해주세요.',to_date('2026-03-12','YYYY-MM-DD'),8,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (85,'JPA의 N+1 문제는 무엇이고 이것이 발생하는 이유와 이를 해결하는 방법을 설명해주세요.',to_date('2026-03-12','YYYY-MM-DD'),8,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (86,'참조복사(얕은복사)와 값복사(깊은복사)의 차이점에 대해 설명해주세요.',to_date('2026-03-12','YYYY-MM-DD'),6,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (87,'HTTP와 HTTPS의 차이점에 대해서 설명해주세요.',to_date('2026-03-16','YYYY-MM-DD'),1,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (88,'멀티스레드 프로그래밍에 대해 설명해주세요.',to_date('2026-03-16','YYYY-MM-DD'),2,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (89,'Spring Web MVC에서 요청 마다 Thread가 생성되어 Controller를 통해 요청을 수행할텐데, 어떻게 1개의 Controller만 생성될 수 있을까요?',to_date('2026-03-16','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (90,'Spring WEB MVC의 근간에는 Java Servlet 이 있는데요. Spring 은 Servlet을 어떻게 구성해서 이를 구현했을까요?',to_date('2026-03-16','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (91,'Filter는 Servlet의 스펙이고, Interceptor는 Spring MVC의 스펙입니다. Spring Application에서 Filter와 Interceptor를 통해 예외를 처리할 경우 어떻게 해야 할까요?',to_date('2026-03-16','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (92,'Spring Application을 구동할 때 메서드를 실행시키는 방법에 대해 설명해주세요.',to_date('2026-03-16','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (93,'의존성과 설정값을 생성자 인자로 주입해야 하는 이유에 대해 설명해주세요.',to_date('2026-03-16','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (94,'[프로젝트] 왜 세션방식이 아닌 JWT 방식을 사용했는지?',to_date('2026-03-16','YYYY-MM-DD'),9,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (95,'[프로젝트] 웹 서버와 WAS의 차이를 설명해주세요.',to_date('2026-03-16','YYYY-MM-DD'),9,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (96,'Spring 애플리케이션의 구동 절차를 아는 대로 설명해주세요.',to_date('2026-03-23','YYYY-MM-DD'),7,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (97,'트랜잭션 격리 수준(Transaction Isolation Levels)에 대해서 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (98,'정규화에 대해서 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (99,'JOIN에 대해서 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),3,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (100,'Stack, Queue에 대해서 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),4,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (101,'Heap, Priority Queue에 대해서 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),4,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (102,'Tree, Binary Tree, BST, AVL Tree에 대해서 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),4,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (103,'OAuth에 대해서 간단히 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),5,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (104,'JWT와 OAuth의 차이는 무엇이 있을까요?',to_date('2026-03-30','YYYY-MM-DD'),5,null);
INSERT INTO QUESTION (ID,QUESTION,ADD_DATE,CATEGORY_ID,TTS_KEY) values (105,'SQL Injection에 대해서 간단히 설명해주세요.',to_date('2026-03-30','YYYY-MM-DD'),5,null);

-- ANSWER 데이터
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (1,1,1,'브라우저에 URL을 입력하면 URL을 해석하고 도메인을 IP로 변환하기 위해 DNS 조회를 수행합니다.
이후 전송 계층에서 TCP 3-way 핸드셰이크로 연결을 수립하고 네트워크/데이터링크 계층에서 라우팅과 MAC 기반 전달을 거쳐 서버까지 패킷이 전달됩니다.
서버는 HTTP 요청을 처리해 응답을 반환하며 클라이언트는 받은 응답으로 화면을 렌더링합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (2,1,2,'프로세스는 실행 중인 프로그램의 인스턴스로 운영체제로부터 독립된 자원과 주소 공간을 할당받아 다른 프로세스와 기본적으로 메모리를 공유하지 않습니다.
스레드는 하나의 프로세스 내부 실행 흐름으로 코드·데이터·힙을 공유하고 스택/레지스터만 분리되며 공유 자원 때문에 동기화가 필요하지만 생성·전환 비용은 일반적으로 프로세스보다 작습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (3,1,3,'데이터베이스에서 인덱스는 테이블을 풀스캔하지 않고 정렬된 별도 구조를 통해 조건에 맞는 레코드를 빠르게 찾아 조회, 조인, 정렬과 그룹핑 성능을 높이기 위해 사용합니다.
장점은 검색·정렬·조인 성능이 향상되는 것이고 단점은 인덱스 저장공간이 추가로 필요하며 INSERT/UPDATE/DELETE 시 인덱스까지 갱신해야 해서 쓰기 성능 저하와 잘못 설계하면 오히려 성능 악화가 발생한다는 점입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (4,1,4,'JVM은 자바 바이트코드를 운영체제와 무관하게 실행하는 가상 머신이며 실행 흐름은 자바 컴파일러가 `.java`를 `.class` 바이트코드로 컴파일한 뒤 JVM이 기동되고 ClassLoader가 클래스를 로딩·검증·링킹하여 main부터 실행하는 방식입니다.
실행 시 초기에는 인터프리터가 바이트코드를 해석해 수행하고 자주 호출되는 코드는 JIT 컴파일러가 네이티브 코드로 컴파일해 캐싱하여 이후 성능을 높입니다.
구조는 크게 메모리 영역(메서드 영역, 힙, 스택, PC 레지스터, 네이티브 메서드 스택)과 실행 엔진(인터프리터, JIT, GC)으로 나뉩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (5,1,5,'GC는 JVM이 힙에서 더 이상 참조되지 않는 객체를 자동으로 찾아 메모리를 회수하는 기능입니다.
수동 메모리 해제에 따른 실수를 줄이고 장시간 실행되는 프로그램에서도 메모리를 효율적으로 관리하기 위해 필요합니다.
루트에서 도달 가능한 객체만 살아있는 것으로 표시하고 나머지를 수거하며 Young/Old 세대 구조로 Young에서 자주(Minor GC), Old에서 크게(Major/Full GC) 처리합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (6,1,6,'컬렉션 프레임워크는 다양한 자료구조를 표준화된 인터페이스와 구현체로 제공하여 공통된 API로 데이터를 저장·조회·삭제·순회·정렬할 수 있게 하는 라이브러리입니다.
상위 인터페이스로 제공 기능을 정의하고 각 구현체가 내부 구조와 성능 특성을 담당하므로 보통 인터페이스 타입으로 코드를 작성해 구현체를 바꿔도 수정이 최소화됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (7,1,7,'제네릭은 클래스·인터페이스·메서드가 사용할 타입을 타입 파라미터로 받아 재사용하게 해주는 기능으로 컴파일 시점에 타입을 명확히 지정해 타입 안정성을 확보합니다.
이를 통해 컬렉션 등에 잘못된 타입이 들어가는 것을 컴파일 단계에서 막고 Object 기반 사용처럼 매번 캐스팅할 필요가 줄어듭니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (8,1,8,'어노테이션은 클래스·메서드·필드 같은 프로그램 요소에 메타데이터를 부여하는 문법으로 해당 요소의 의미나 설정 정보를 컴파일러·런타임 프레임워크·빌드 도구에 전달합니다.
즉 코드의 로직을 직접 바꾸기보다는 검사, 설정, 자동 처리 같은 동작이 가능하도록 보조 정보를 제공하는 역할을 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (9,1,9,'오버라이딩은 상속 관계에서 자식 클래스가 부모 메서드를 같은 이름으로 재정의하여 다형성을 구현하는 것으로 어떤 메서드가 호출될지는 런타임에 동적 바인딩으로 결정됩니다.
오버로딩은 같은 이름의 메서드를 파라미터 목록(타입/개수)을 달리해 여러 개 정의하는 것으로 호출될 메서드는 컴파일 시점에 정적 바인딩으로 결정되며 반환 타입만으로는 구분할 수 없습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (10,1,10,'DNS는 도메인 이름을 IP 주소로 변환해주는 인터넷의 전화번호부 시스템입니다.
사용자가 주소를 입력하면 DNS 서버가 루트, TLD, 네임 서버를 차례로 방문하며 해당 도메인의 위치를 찾아냅니다.
최종적으로 찾아낸 IP 주소를 브라우저에 전달하면 컴퓨터는 해당 서버와 연결되어 웹페이지를 불러오게 됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (11,1,11,'인터넷에서 데이터와 통신을 안전하게 보호하는 암호화 프로토콜로 HTTPS의 핵심 기반입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (12,1,12,'네트워크에서 논리적인 IP 주소를 물리적인 MAC 주소로 변환하는 통신 프로토콜입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (13,1,13,'패킷 수신 측은 1계층에서 물리적 신호를 받아서 7계층 순으로 올라가며 헤더를 하나씩 벗겨내어 순수한 데이터를 추출합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (14,3,2,'프로세스는 OS로부터 할당받은 독립된 메모리 공간을 가지는 실행 단위로 코드, 데이터, 힙, 스택 영역으로 구성되어있고, 스레드는 프로세스 내부에서 자원을 공유하며 실행되는 작업 단위로 스택과 레지스터만 독립적으로 갖습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (15,2,2,'프로세스는 운영체제로부터 자원을 할당 받는 작업의 단위이고 스레드는 그 프로세스 내에서 실행되는 흐름의 단위입니다.

가장 큰 차이점은 메모리 공유입니다. 프로세스는 독립된 메모리 공간을 가지지만 스레드는 Code, Data, Heap영역을 공유하고 Stack, 레지스터 영역을 독립적으로 가집니다.

이 때문에 스레드 간 전환이 프로세스보다 훨씬 빠르고 효율적이지만 스레드 하나에 문제가 생기면 프로세스 전체가 죽을 수 있다는 안정성 문제도 존재합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (16,3,8,'''@'' 기호를 사용하여 특별한 의미나 기능을 부여하는 ''메타데이터(데이터에 대한 데이터)''입니다. 프로그램에 추가 정보를 제공하여 코드의 역할을 명시하거나, 컴파일러 및 프레임워크에게 실행 지침을 주는 주석 역할을 수행합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (17,1,14,'코드 영역: 실행할 프로그램의 기계어 코드(명령어)가 저장됩니다.
데이터 영역: 프로그램 시작부터 종료까지 유지되는 전역 변수(Global), 정적 변수(Static), 상수(Constant)가 저장됩니다.
힙 영역: 프로그래머가 동적으로 할당하는 메모리 공간(예: C언어의 malloc, Java의 new)입니다.
스택 영역: 함수 호출 시 생성되는 지역 변수, 매개변수, 반환 주소(Return Address) 등 일시적인 데이터가 저장됩니다.
레지스터 영역: 프로그램 카운터, 현재 CPU 상태');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (18,1,15,'스레드들이 프로세스의 자원(메모리 등)을 공유하기 때문입니다. 하나의 스레드가 잘못된 메모리 영역에 접근하거나 치명적인 예외를 발생시키면 공유 자원이 오염되거나 프로세스 전체의 안정성이 깨지게 됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (19,1,16,'전체 시스템의 성능이나 처리 용량이 특정 구성 요소의 제한으로 인해 낮아지는 현상을 말합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (20,1,17,'둘 이상의 프로세스나 스레드가 공용 자원에 동시 접근하여 실행 순서에 따라 결과가 달라지는 현상을 말합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (21,1,18,'운영체제에서 실행 중인 서로 다른 프로세스들 사이에 데이터를 주고받는 방식입니다. 대표적으로 메시지 큐나 소켓 등이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (22,1,19,'데이터 전체에 중복이 거의 없고 유니크한 값이 많은 컬럼을 의미합니다. 예시로는 이메일이나 주민등록번호 등이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (23,1,20,'SQL 쿼리를 가장 빠르고 효율적으로 실행하기 위해 최적의 처리 경로를 수립하는 핵심 엔진입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (24,1,21,'자바에서 C나 C++로 만들어진 라이브러리를 사용할 수 있게 해주는 인터페이스입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (25,1,22,'메서드 영역: 클래스 정보, 변수 이름, 데이터 타입, static 변수, 메소드 코드 등이 저장됩니다.
힙 영역: 프로그램 실행 중 동적으로 생성되는 객체(인스턴스)와 배열이 저장됩니다.
스택 영역: 지역 변수, 매개 변수, 리턴 값 등 연산 과정의 임시 데이터가 저장됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (26,1,23,'- 객체 생성 (Eden): new로 생성된 새로운 객체는 Eden 영역에 할당됩니다.
- Minor GC 1차 (Eden -> Survivor): Eden 영역이 가득 차면 Minor GC가 발생합니다. 살아남은 객체는 Survivor 영역 중 하나(예: S0)로 이동하고 Eden 영역은 비워집니다.
- Minor GC 2차 이상 (Survivor -> Survivor): 또 다른 Minor GC가 발생하면, Eden에서 살아남은 객체와 이전 Survivor(S0)에서 살아남은 객체를 다른 Survivor 영역(S1)으로 복사합니다. 이 과정에서 S0는 비워지고 S1에만 객체가 존재하게 됩니다 (S0과 S1은 핑퐁처럼 역할을 교대함).
- Old Generation 이동/승격 (Promotion): Survivor 영역에서 살아남은 객체들은 ''Age''가 증가합니다. 특정 횟수(Threshold) 이상 생존한 객체는 Old Generation으로 이동합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (27,1,24,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (28,1,25,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (29,1,26,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (30,1,27,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (31,1,28,'배열은 동일한 타입의 요소를 연속된 메모리 공간에 저장하므로 인덱스로 O(1)에 임의 접근이 가능하지만 중간 삽입/삭제 시 요소 이동이 필요해 O(n)이 걸립니다.
링크드 리스트는 노드가 비연속 메모리에 분산되고 포인터로 연결되어 임의 접근은 O(n)이지만 위치를 알고 있다면 포인터만 변경하여 삽입/삭제를 O(1)에 수행할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (32,1,29,'비대칭키 암호화는 두 개의 서로 다른 키를 사용하여 데이터를 암호화/복호화하는 암호화 방법입니다. 대칭키 암호화에 비해 느리지만 비교적 안전하다는 장점이 있습니다.
대칭키 암호화는 데이터의 암호화와 복호화에 동일한 비밀 키를 사용하는 방법입니다. 키 전달 중 탈취의 위험이 있지만 비대칭키 암호화에 비해 빠르다는 장점이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (33,1,30,'Spring에서 IoC는 객체의 생성과 생명주기 관리, 의존관계 설정을 개발자가 직접 하지 않고 외부에서 담당하도록 제어 흐름을 역전시키는 개념입니다.
DI는 IoC를 구현하는 방식으로 필요한 객체를 직접 생성하지 않고 컨테이너가 생성한 빈(Bean)을 생성자 주입·필드 주입·setter 주입 등의 방식으로 주입받아 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (34,1,31,'추상 클래스는 공통 기능과 필드를 함께 묶어 상속 기반으로 재사용하고 필요한 경우 추상 메서드를 통해 하위 클래스가 구현해야 할 기능을 강제하는 목적의 클래스입니다.
인터페이스는 클래스의 상속 계층과 무관하게 특정 기능의 규약을 정의하여 구현 객체가 같은 동작을 제공함을 보장하고 여러 인터페이스를 다중 구현하여 다형성을 확장하는 데 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (35,1,32,'클래스는 객체를 만들기 위한 설계도로서 객체가 가져야 할 속성과 동작을 정의한 틀입니다.
객체는 데이터와 그 데이터를 처리하는 기능을 함께 지닌 독립된 실체이고 클래스에 의해 생성된 객체를 인스턴스라고 부릅니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (36,1,33,'static은 특정 객체에 속하는 값이 아니라 클래스에 고정되어 공유되는 멤버를 의미합니다.
클래스가 로딩될 때 메모리에 한 번 적재되어 인스턴스 생성 없이 접근 가능하며 프로그램 종료 시까지 유지되면서 여러 객체가 같은 값을 공유합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (37,1,34,'boolean과 byte가 1바이트, char와 short가 2바이트, int와 float가 4바이트, long과 double이 8바이트를 차지합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (38,1,35,'접근 제어자는 public, protected, default, private가 있으며 클래스/필드/메서드의 접근 범위를 제한하는 기능입니다.
public은 어디서나 접근 가능하고 protected는 같은 패키지 또는 다른 패키지의 자식 클래스에서 접근 가능하며 default는 같은 패키지에서만 private는 선언한 클래스 내부에서만 접근 가능합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (39,1,36,'객체지향은 프로그램을 상태와 행동을 가진 객체들의 상호작용으로 바라보고 기능을 구성하는 프로그래밍 패러다임입니다.
4대 특징은 캡슐화/추상화/상속/다형성으로 캡슐화는 내부 구현을 숨겨 변경 영향을 줄이고 추상화는 공통 개념을 뽑아 역할 중심으로 설계하며 상속은 공통 기능을 재사용/확장하는 방법입니다.
다형성은 동일한 인터페이스로 호출해도 구현체에 따라 동작이 달라지게 하여 유연한 확장과 유지보수성을 높이는 방법입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (40,1,37,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (41,1,38,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (42,1,39,'JPA 영속성 컨텍스트의 이점은 5가지입니다.
첫째, 엔티티 조회 시 영속성 컨텍스트의 1차 캐시로 같은 식별자의 엔티티를 재사용하여 DB 접근 횟수를 줄입니다.
둘째, 같은 PK로 조회한 엔티티는 항상 같은 인스턴스로 관리되어 동일성이 보장되고 엔티티 간의 비교나 컬렉션 관리가 안정적입니다.
셋째, 쓰기 지연으로 DML SQL을 커밋 직전까지 모아두었다가 flush/commit 시점에 실행해 DB 작업을 최적화합니다.
넷째, 영속 상태 엔티티는 변경 감지가 적용되어 값만 변경하면 자동으로 UPDATE가 반영되므로 코드 작성 시 SQL 작성과 호출이 줄어 실수를 줄입니다.
다섯째, 지연 로딩을 통해 연관 객체를 실제로 사용할 때만 조회하여 불필요한 조인을 줄이고 초기 조회 성능을 개선합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (43,1,40,'TCP는 3-way 핸드셰이크로 연결을 수립하고 시퀀스/ACK 기반으로 재전송과 순서 보장, 흐름 제어, 혼잡 제어를 제공하여 신뢰성 있는 전송을 지원합니다.
반면 UDP는 연결 없이 데이터그램을 전송하며 전달 보장·순서 보장·흐름/혼잡 제어가 없지만 헤더가 단순해 오버헤드가 적고 지연이 작습니다.
따라서 TCP는 안정성이 중요한 서비스에 적합하고 UDP는 실시간성과 빠른 전송이 중요한 상황에 적합합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (44,1,41,'컨텍스트 스위칭은 CPU가 실행 중이던 프로세스나 스레드의 상태 정보를 저장하고 다른 작업의 상태 정보를 복원하여 실행 주체를 교체하는 과정입니다.
커널이 이를 수행함으로써 여러 작업이 동시에 실행되는 것처럼 보이게 하고 공정한 CPU 시간 분배와 우선순위 기반 처리를 가능하게 합니다.
주로 타임 슬라이스 만료, I/O 대기, 자원 대기, 인터럽트 발생 등의 상황에서 일어납니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (45,1,42,'SOLID는 객체지향 설계에서 지켜야 할 5가지 원칙으로 유지보수성과 확장성을 높이기 위한 지침입니다.
SRP는 단일 책임 원칙으로 클래스가 하나의 책임만 가지도록 하여 수정 시 연쇄 변경을 줄이는 원칙입니다.
OCP는 개방 폐쇄 원칙으로 기능 추가를 기존 코드 수정이 아닌 확장으로 해결하도록 하며 추상화와 다형성을 활용해 변경에 강한 구조를 만듭니다.
LSP는 리스코프 치환 원칙으로 자식 타입이 부모 타입을 대체해도 동작이 의도대로 유지되도록 오버라이딩 시 계약을 깨지 않게 하는 원칙이고,
ISP는 인터페이스 분리 원칙으로 인터페이스를 사용하는 코드에서 필요로 하는 기능만 가진 작은 인터페이스로 분리하는 원칙입니다.
DIP는 의존 역전 원칙으로 구체 구현이 아니라 추상에 의존하게 하여 결합도를 낮추고 변경에 유연한 구조를 만드는 원칙입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (46,1,43,'동일성은 두 객체가 메모리 상에서 완전히 같은 인스턴스인지를 비교하는 개념으로 == 연산자로 판단합니다.
동등성은 두 객체가 서로 다른 인스턴스일 수 있어도 값이 논리적으로 같은지를 비교하는 개념으로 equals() 메서드로 판단합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (47,1,44,'원시 타입은 실제 데이터 값 자체를 저장하며 null을 가질 수 없고 제네릭 타입에 사용할 수 없습니다. 일반적으로 참조 타입보다 메모리 사용이 적고 접근이 빠릅니다.
참조 타입은 객체의 메모리 주소를 저장해 실제 객체를 가리키며 null이 가능하고 제네릭에서 사용할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (48,1,45,'String은 불변 객체라 문자열 변경 시 새로운 객체가 생성되어 변경이 잦으면 성능이 떨어질 수 있습니다.
StringBuilder와 StringBuffer는 내부 버퍼를 이용하는 가변 문자열로 변경 시 같은 객체를 수정하므로 문자열 조작이 많은 경우에 유리합니다.
둘의 차이는 StringBuffer는 동기화를 제공해서 멀티스레드에서 비교적 안전하고 StringBuilder는 동기화가 없어 단일 스레드에서 더 빠르다는 점입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (49,1,46,'Checked Exception은 컴파일 시점에 예외 처리를 강제하여 try-catch로 처리하거나 throws로 위임해야 하는 예외입니다.
Unchecked Exception은 런타임에 발생하고 컴파일러가 처리를 강제하지 않는 예외입니다.
스프링 트랜잭션에서 기본 롤백 대상은 Unchecked Exception 및 Error이며 Checked Exception은 기본적으로 롤백하지 않습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (50,1,47,'Java 8에서는 람다 표현식과 함수형 인터페이스가 도입되어 함수를 값처럼 전달하고 간결하게 동작을 표현할 수 있게 되었습니다.
또한 Stream API가 추가되어 컬렉션 데이터를 filter/map/collect 같은 파이프라인으로 선언형 처리할 수 있고 Optional로 null 가능성을 명시적으로 다뤄 null 참조 예외를 줄일 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (51,1,48,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (52,1,49,'이은상의 답');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (53,1,50,'트랜잭션은 데이터베이스의 상태를 변화시키는 작업들을 하나로 묶은 논리적 단위입니다.
4대 원칙인 ACID(원자성·일관성·격리성·지속성)를 통해 작업이 전부 처리되거나 전부 취소되고 무결성과 격리를 유지하며 커밋된 결과는 영구적으로 보존되도록 보장합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (54,1,51,'List는 저장 순서가 유지되고 중복을 허용하며 인덱스로 특정 위치에 접근할 수 있습니다.
Set은 인덱스가 없고 중복을 허용하지 않으며 `equals()`와 `hashCode()` 기준으로 유일성을 보장해 중복 제거와 포함 여부 확인에 적합합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (55,1,52,'단방향 암호화는 평문을 해시 값으로 변환할 수는 있지만 해시 과정에서 정보가 손실되어 복호화로 원문을 되돌릴 수 없는 방식입니다.
주로 무결성 검증과 비밀번호 저장에 활용됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (56,1,53,'try-with-resources는 Java 7부터 도입된 문법으로 try문에서 선언한 AutoCloseable/Closeable 자원을 블록 종료 시 자동으로 close()하여 finally에서 직접 닫지 않아도 되는 문법입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (57,1,54,'강한 결합은 한 클래스가 다른 클래스의 구현체에 직접 의존하여 내부에서 new로 생성하거나 구체 타입을 고정하는 상태로 의존 대상이 바뀌면 수정 범위가 커져 유지보수가 어려워집니다.
느슨한 결합은 구현체 대신 인터페이스 같은 추상화에 의존하고 의존 객체를 외부에서 주입받아서 구현체를 교체하거나 추가해도 기존 코드 변경을 최소화하는 구조입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (58,1,55,'직렬화는 자바 객체의 상태를 저장·전송 가능한 바이트 스트림으로 변환하는 과정이고 역직렬화는 이를 다시 읽어 자바 객체로 복원하는 과정입니다.
이때 대상 클래스는 Serializable 인터페이스를 구현해야 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (59,1,56,'자바의 동시성 이슈는 멀티 스레드 환경에서 여러 스레드가 공유 자원에 동시에 접근하면서 기대한 값이 나오지 않거나 스레드마다 서로 다른 값을 보게 되는 문제입니다.
대표적으로 연산이 분해되며 발생하는 원자성 문제와 캐시/메모리 반영 지연으로 생기는 가시성 문제가 있으며 각각 동기화(락)와 volatile 키워드 등으로 해결합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (60,1,57,'Mutable 객체는 가변객체로 생성 이후에도 같은 인스턴스의 내부 상태를 직접 변경할 수 있습니다.
Immutable 객체는 불변객체로 생성 이후 상태를 바꿀 수 없고 변경이 필요하면 새 객체를 만들어 참조를 바꾸는 방식입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (61,1,58,'자바에서 null을 안전하게 다루려면 사용 전 null 체크를 하거나 `Objects.requireNonNull`로 입력 계약을 강제해 null 참조를 빠르게 발견하도록 합니다.
또한 값이 없을 수 있음을 Optional로 명시해 기본값 처리나 예외 처리로 흐름을 관리하고 래퍼 타입의 언박싱으로 인한 null 참조를 주의해야 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (62,1,59,'스프링 빈은 스프링 IoC 컨테이너가 생성·등록·관리하는 자바 객체로, 개발자가 `new`로 직접 만들던 객체들을 컨테이너가 대신 생성해 필요한 곳에 주입해주는 대상입니다.
이를 통해 의존관계를 컨테이너가 관리하여 결합도를 낮추고 라이프사이클 관리까지 지원해 구조를 유연하게 만듭니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (63,1,60,'스프링 빈은 IoC 컨테이너가 생성한 뒤 의존관계를 주입하고 초기화 콜백을 거쳐 사용되다가 컨테이너 종료 시점에 소멸 전 콜백으로 자원을 정리하는 과정을 가집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (64,1,61,'스프링 Bean 스코프는 빈이 생성되고 유지되는 라이프사이클 범위를 의미합니다.
종류는 컨테이너 전체에서 1개 인스턴스를 공유하는 싱글톤, 요청마다 새 인스턴스를 만드는 프로토타입, 그리고 웹 환경에서 요청/세션/애플리케이션/웹소켓 범위로 유지되는 웹 스코프가 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (65,1,62,'IoC 컨테이너는 설정 정보를 바탕으로 빈을 생성·등록하고 빈 사이의 의존관계를 분석해 필요한 객체를 자동으로 주입합니다. 또한 빈의 생명주기와 스코프를 관리합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (66,1,63,'JPA의 Propagation은 이미 진행 중인 트랜잭션이 있을 때 다른 트랜잭션의 수행 방식을 정하는 전파 옵션입니다.
대표적으로 트랜잭션이 있으면 참여하고 없으면 생성하는 REQUIRED(기본), 있으면 참여하고 없으면 트랜잭션 없이 수행하는 SUPPORTS 등의 옵션이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (67,1,64,'3-way handshake는 데이터 전송 전에 클라이언트와 서버가 서로 연결 요청 플래그를 교환하여 통신 가능함을 확인하고 연결을 수립하는 과정입니다.
4-way handshake는 통신 종료 시 연결 종료 요청을 주고받아 양측이 종료에 합의하고 연결을 정상적으로 해제하는 과정입니다.

- SYN (Synchronize): 연결 설정 요청 플래그  
- FIN (Finish): 연결 종료 요청 플래그');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (68,1,65,'JRE는 자바 프로그램을 실행하기 위한 환경으로 JVM과 표준 라이브러리를 포함하지만 컴파일러 같은 개발 도구는 포함하지 않습니다.
JDK는 자바 프로그램을 개발하고 실행하기 위한 키트로, JRE에 더해 개발 도구를 포함합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (69,1,66,'Access Token과 Refresh Token을 나눈 이유는 통신 중 탈취될 위험이 큰 Access Token은 유효기간을 짧게 가져가 피해를 최소화하고 대신 Refresh Token으로 Access Token을 재발급해서 사용자가 자주 재로그인하지 않도록 하기 위해서입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (70,1,67,'WebSocket을 사용한 이유는 실시간으로 메시지를 주고받아야 하는 상황에서 HTTP의 요청-응답 구조는 지연과 트래픽 오버헤드가 커지기 때문입니다.
WebSocket은 한 번 연결을 수립하면 연결을 유지한 채 양방향으로 서버가 메시지를 즉시 전송할 수 있어서 지연을 줄이고 효율적으로 실시간 채팅을 구현할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (71,1,68,'폴링이나 롱 폴링, SSE 등의 방법이 있지만 웹소켓의 실시간성과 양방향 통신이라는 특징이 저희 프로젝트에 적합하다고 판단해서 웹소켓을 사용했습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (72,1,69,'스프링의 DI 방식에는 생성자 주입, setter 주입, 필드 주입이 있습니다.
생성자 주입은 의존성이 생성자에 드러나고 생성 시점에 주입이 완료되어 final로 불변 설계를 하기 좋은 방식입니다.
setter 주입은 선택 의존성이나 교체가 필요한 경우에 유용하고, 필드 주입은 코드가 간단하지만 의존성이 숨겨져 테스트와 유지보수에 불리한 방식입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (73,1,70,'컨테이너가 빈을 생성한 뒤 @Autowired가 붙은 주입 지점을 찾아 의존 타입에 맞는 빈을 검색해 주입하고 이후 초기화 단계로 넘어갑니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (74,1,71,'DispatcherServlet은 모든 HTTP 요청을 먼저 받아 HandlerMapping으로 처리할 컨트롤러를 찾고 HandlerAdapter를 통해 해당 컨트롤러를 호출해 처리 결과를 얻는 방식으로 동작합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (75,1,72,'동기는 호출한 쪽이 작업 결과를 받을 때까지 기다리는 방식이라 제어 흐름이 직관적이고 디버깅이 쉽지만 결과가 늦으면 대기 비용으로 처리량이 떨어질 수 있습니다.
비동기는 결과를 즉시 기다리지 않고 완료 시점에 콜백/이벤트 등으로 처리해 대기 시간 동안 다른 작업을 수행할 수 있어 효율적일 수 있으나 동기식보다 설계가 복잡해질 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (76,1,73,'ACID는 트랜잭션이 지켜야 할 4가지 성질로 원자성, 일관성, 격리성, 지속성이 있습니다.
원자성은 트랜잭션의 작업이 모두 성공하거나 모두 실패하도록 보장하는 것입니다.
일관성은 트랜잭션 전후에도 데이터가 무결성 제약을 만족하는 일관된 상태를 유지하는 것을 의미합니다.
격리성은 동시에 실행되는 트랜잭션들이 서로의 작업에 영향을 주지 않도록 독립적으로 수행되게 하는 성질입니다.
지속성은 커밋이 완료된 변경 결과가 장애가 발생해도 영구적으로 반영되도록 보장하는 성질입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (77,1,74,'final은 변경을 제한하는 키워드로, 변수에 붙이면 한 번만 초기화되고 재할당이 불가하며 메서드에 붙이면 오버라이딩이 금지되고 클래스에 붙이면 상속이 금지됩니다.
이를 통해 변경 가능성을 줄여 의도를 명확히 하고 실수를 예방해 코드의 안정성과 유지보수성을 높입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (78,1,75,'Wrapper class는 기본형을 객체로 다룰 수 있게 감싸는 클래스입니다.
컬렉션·제네릭처럼 객체만 받을 수 있는 곳에서 기본형을 사용하기 위해 쓰고 필요하면 null로 값 없음도 표현할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (79,1,76,'Access Token은 프론트에서 사용자 이름/권한 같은 정보를 확인하거나 요청 헤더에 실어 보내는 등 활용도가 높은데 HttpOnly 쿠키에 저장하면 자바스크립트가 접근할 수 없어 이런 처리가 불편해집니다.
**대처방법 쓰기**');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (80,1,77,'WebSocket은 연결만 제공해서 메시지 형식이나 라우팅 규칙을 직접 설계해야 하는데 STOMP를 사용하면 SEND/SUBSCRIBE 같은 표준 프레임과 Pub/Sub 구조로 채팅 메시지 흐름을 일관되게 정의할 수 있습니다.
그래서 방 구독, 브로드캐스트 같은 기능을 구현·확장하기 쉬워지고 디버깅과 유지보수도 수월해집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (81,1,78,'프론트 컨트롤러 패턴은 모든 요청을 하나의 진입점에서 먼저 받아 공통 처리를 수행한 뒤 요청에 맞는 개별 컨트롤러로 위임하는 구조입니다.
이를 통해 중복 코드를 줄이고 요청 처리 흐름을 일관되게 관리할 수 있습니다.
스프링 MVC에서는 이를 DispatcherServlet으로 구현합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (82,1,79,'Servlet Filter는 Servlet 앞단에서 동작하므로 웹 애플리케이션 전반의 공통 처리를 담당하기에 적합합니다.
반면 Spring Interceptor는 Servlet과 Controller 사이에서 동작하는 기능으로 MVC 흐름과 밀접한 공통 로직 처리에 적합합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (83,1,80,'Spring에서 CORS 에러를 해결하려면 특정 컨트롤러나 메서드에 @CrossOrigin을 붙이거나 WebMvcConfigurer의 addCorsMappings()로 전역 설정을 적용하는 방식이 있습니다.
만약 Spring Security를 사용한다면 보안 설정에도 CORS 허용을 함께 반영해야 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (84,1,81,'POJO는 특정 기술이나 프레임워크에 종속되지 않고 객체지향 원리에 따라 작성된 순수한 자바 객체입니다.
Spring에서는 서비스, 도메인 객체, 컨트롤러 같은 클래스가 스프링 규약에 과하게 의존하지 않고 핵심 로직을 담고 있다면 POJO가 될 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (85,1,82,'Hash Function은 임의의 키를 해시값으로 변환하는 함수입니다.
Hash Table은 이렇게 계산한 해시값을 이용해 키와 값을 저장하는 자료구조입니다.
이때 서로 다른 키가 같은 해시값을 가지는 충돌이 발생할 수 있어서 체이닝이나 개방 주소법 같은 충돌 해결 방식이 필요합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (86,1,83,'JWT는 JSON 기반의 정보를 담고 서명한 토큰으로, 주로 인증과 권한 부여에 사용되는 토큰 방식입니다.
토큰은 Header.Payload.Signature 구조로 이루어지며 서버는 서명과 만료 시간 등을 검증해 사용자를 인증합니다.
세션을 서버에 저장하지 않고도 stateless하게 인증을 처리할 수 있다는 장점이 있지만 토큰이 탈취되면 위험하므로 만료 시간 관리가 중요합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (87,1,84,'JPA를 사용하는 이유는 반복적인 SQL 작성과 JDBC 기반 매핑 작업을 줄여 CRUD를 메서드 호출 중심으로 처리할 수 있어 개발 생산성이 높아지기 때문입니다.
또한 엔티티 중심으로 도메인 모델을 설계하고 관리할 수 있어 비즈니스 로직을 객체지향적으로 작성하기 좋고 엔티티 필드가 바뀌었을 때 관련 SQL을 일일이 수정하지 않아도 되어 유지보수에도 유리합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (88,1,85,'JPA의 N+1 문제는 연관 엔티티를 조회할 때 처음 1번의 조회 쿼리 이후 조회된 엔티티 수만큼 추가 쿼리가 발생하는 문제입니다.
이유는 JPA의 JPQL 조회가 기본적으로 루트 엔티티 중심으로만 쿼리를 만들고 연관 엔티티는 이후 접근 시점에 별도로 조회하기 때문입니다.
해결 방법으로는 fetch join이나 @EntityGraph를 사용해 연관 엔티티를 한 번에 함께 조회하도록 명시하는 방식이 대표적입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (89,1,86,'참조복사(얕은복사)는 객체의 참조값만 복사해서 원본과 복사본이 같은 객체를 바라보는 방식입니다. 그래서 복사본의 상태를 변경하면 원본에도 같은 변경이 반영됩니다.
반면 값복사(깊은복사)는 새로운 객체를 생성해 내부 값까지 별도로 복사하므로 복사본을 수정해도 원본에는 영향을 주지 않습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (90,1,87,'HTTP는 데이터를 평문으로 전송하는 요청-응답 프로토콜이라 중간에서 내용을 탈취하거나 변조할 위험이 있습니다.
반면 HTTPS는 HTTP에 SSL이나 TLS를 적용해서 데이터를 암호화하고 서버 인증을 수행하므로 기밀성과 무결성을 더 잘 보장합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (91,1,88,'멀티스레드 프로그래밍은 하나의 프로세스 안에서 여러 스레드가 동시에 작업을 수행하도록 하는 프로그래밍 방식으로 스레드들은 같은 프로세스의 자원을 공유하면서 각자 실행 흐름을 가집니다.
이를 통해 응답성을 높이고 자원 공유를 쉽게 할 수 있지만 동기화 문제나 동시성 이슈에 주의해야 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (92,1,89,'Spring MVC의 컨트롤러는 기본적으로 싱글톤 Bean으로 관리되어서 요청이 여러 번 들어와도 컨트롤러 인스턴스는 하나만 생성되기 때문입니다.
각 요청은 별도의 스레드가 처리하지만 그 스레드들이 같은 컨트롤러 Bean의 메서드를 호출하는 방식으로 동작합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (93,1,90,'Spring Web MVC는 여러개의 서블릿을 직접 두는 대신 DispatcherServlet이라는 하나의 Front Controller Servlet이 모든 요청을 먼저 받도록 구성했습니다.
이후 DispatcherServlet이 요청을 적절한 Controller에 위임하고 처리 결과를 반환합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (94,1,91,'필터는 서블릿 영역에서 동작하므로 여기서 발생한 예외는 필터 내부에서 직접 try-catch로 응답을 만들거나 에러 처리 경로로 넘겨야 합니다.
반면 Interceptor는 Spring MVC 영역에서 동작하므로 @ControllerAdvice 같은 스프링 예외 처리 방식으로 처리할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (95,1,92,'대표적인 방법으로는 Bean 초기화 직후 실행되는 @PostConstruct와 애플리케이션이 완전히 시작된 뒤 실행되는 CommandLineRunner 또는 ApplicationRunner가 있습니다.
이 외에도 InitializingBean의 afterPropertiesSet() 같은 방법을 사용할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (96,1,93,'객체가 생성되는 시점에 필요한 값이 모두 들어와 완전한 상태로 생성되도록 보장할 수 있기 때문입니다.
또한 생성자 매개변수만 봐도 어떤 의존성과 설정값이 필요한지 명확히 드러나고 final과 함께 사용하면 불변성을 유지하기 쉬워집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (97,1,94,'세션 방식은 로그인 상태를 서버 메모리나 세션 저장소에 보관해야 해서 사용자가 많아질수록 서버 부하도 커집니다.
반면 JWT는 인증 정보를 토큰 자체에 담아 클라이언트가 저장하므로 서버는 매 요청마다 세션 저장소를 조회하지 않고 토큰 검증만으로 인증을 처리할 수 있기 때문에 JWT 방식을 사용했습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (98,1,95,'웹 서버는 HTTP 요청을 받아 정적 리소스를 전달하는 역할에 적합합니다.
반면 WAS는 비즈니스 로직, 데이터베이스 연동, 동적 콘텐츠 생성처럼 애플리케이션 처리에 적합합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (99,1,96,'Spring 애플리케이션은 main() 메서드에서 SpringApplication.run()을 호출하면서 시작되며 이때 스프링 부트가 애플리케이션 타입을 판단하고 실행에 필요한 Environment와 ApplicationContext를 준비합니다.
그다음 @SpringBootApplication을 기준으로 컴포넌트 스캔이 수행되어 빈 후보들이 수집되고 @EnableAutoConfiguration을 통해 클래스패스와 설정 파일을 바탕으로 필요한 자동 설정이 적용됩니다.
이후 스프링 컨테이너가 빈 정의를 등록하고 실제 빈을 생성하면서 의존성 주입을 수행하고 초기화 콜백까지 처리합니다.
이 과정이 끝나면 ApplicationContext가 refresh 되면서 컨테이너가 완성되고 웹 애플리케이션인 경우에는 내장 톰캣 같은 서버도 함께 기동되어 HTTP 요청을 받을 수 있는 상태가 됩니다.
마지막으로 애플리케이션 시작이 완료된 뒤 CommandLineRunner 같은 후처리 로직이 실행될 수 있습니다.
정리하면 SpringApplication.run()을 시작으로 환경 준비, 컨텍스트 생성, 컴포넌트 스캔과 자동 설정, 빈 생성과 의존성 주입, 컨텍스트 refresh, 내장 서버 기동 순서로 애플리케이션이 구동됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (100,1,97,'트랜잭션 격리 수준은 동시에 여러 트랜잭션이 실행될 때 서로의 변경 내용을 어디까지 볼 수 있게 할지를 정하는 기준입니다.
READ UNCOMMITTED는 커밋되지 않은 데이터도 읽을 수 있고 READ COMMITTED는 Dirty Read를 막지만 반복 조회 시 값이 달라질 수 있습니다.
REPEATABLE READ는 같은 데이터를 다시 읽었을 때 값이 바뀌지 않도록 보장하지만 Phantom Read 가능성은 남아 있고 SERIALIZABLE은 가장 엄격한 수준으로 트랜잭션을 거의 순차 실행처럼 처리합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (101,1,98,'정규화는 데이터 중복을 줄이고 데이터 구조를 올바르게 분리해서 무결성을 높이는 과정입니다.
이를 통해 삽입, 수정, 삭제 과정에서 발생할 수 있는 이상 현상을 방지하고 데이터를 더 일관성 있게 관리할 수 있습니다.
다만 정규화를 많이 하면 조회 시 JOIN이 늘어 성능에 영향을 줄 수 있어서 상황에 따라 정규화 단계를 설정해야 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (102,1,99,'JOIN은 분리된 여러 테이블을 공통 컬럼을 기준으로 연결해 원하는 데이터를 함께 조회하는 방법입니다.
이를 통해 분리된 데이터를 효율적으로 함께 조회할 수 있지만 JOIN이 많아질수록 쿼리가 복잡해지고 조회 성능이 저하될 수 있다는 단점도 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (103,1,100,'스택과 큐는 대표적인 선형 자료구조입니다.
스택은 후입선출 구조로 가장 나중에 들어온 데이터가 먼저 나가서 브라우저 뒤로가기나 함수 호출 스택 등에 사용됩니다.
큐는 선입선출 구조로 가장 먼저 들어온 데이터가 먼저 나가서 BFS나 메시지 큐 등에 사용됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (104,1,101,'우선순위 큐는 우선순위가 높은 데이터가 먼저 나가는 자료구조입니다.
힙은 우선순위 큐를 효율적으로 구현하기 위한 완전이진트리 기반의 자료구조로, 우선순위가 가장 높은 데이터를 빠르게 조회하고 삭제할 수 있다는 특징이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (105,1,102,'Tree는 노드와 간선으로 이루어진 계층형 비선형 자료구조입니다.
Binary Tree는 Tree의 한 종류로 각 노드가 최대 두 개의 자식만 가질 수 있는 구조입니다.
BST는 이진 트리에 정렬 규칙이 추가된 형태로, 왼쪽 서브트리에는 작은 값, 오른쪽 서브트리에는 큰 값을 저장합니다.
AVL 트리는 BST의 한 종류로, 삽입과 삭제 후에도 균형을 자동으로 맞춰서 최악의 경우에도 안정적으로 O(log n) 성능을 유지합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (106,1,103,'OAuth는 사용자의 아이디와 비밀번호를 직접 넘기지 않고 특정 리소스에 대한 접근 권한만 토큰 형태로 위임할 수 있게 해주는 인가 표준입니다.
대표적으로 소셜 로그인에서 사용되며 서비스는 사용자의 비밀번호 대신 Access Token을 이용해 허용된 범위의 정보만 접근할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (107,1,104,'JWT는 서버가 토큰에 사용자 정보와 권한을 담아 직접 인증을 처리하는 방식이고 주로 자체 로그인 이후 stateless한 인증에 사용됩니다.
반면 OAuth는 사용자의 비밀번호를 직접 받지 않고 외부 서비스가 발급한 토큰을 통해 제한된 권한을 위임받는 인가 표준입니다.
따라서 JWT와 달리 OAuth는 제3자 서비스에 대한 권한 위임에 초점이 있다는 점이 가장 큰 차이입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (108,1,105,'SQL Injection은 사용자 입력값이 검증되지 않은 채 SQL 쿼리에 직접 포함될 때 공격자가 SQL 문을 주입해 데이터베이스를 비정상적으로 조작하는 공격입니다.
대표적인 대응 방법으로는 Prepared Statement 같은 매개변수화된 쿼리를 사용해 입력값과 SQL 구조를 분리하는 방법이 있고, 입력값 검증과 최소 권한 원칙을 함께 적용해 피해 가능성을 줄일 수도 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (121,3,1,'사용자가 웹브라우저에 URL을 입력하면 DNS를 통해 IP로 변환하고 http''s''의 경우 TCP와 서버와 클라이언트간의 인증 및 암호화 키를 공유하여 안전한 통신 채널을 만드는 과정인 TLS을 통해 안정적인 연결을 맺은 후 HTTP요청/응답을 통해 서버로부터 자원을 받아와 화면에 렌더링하는 과정을 거치게됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (122,3,3,'WHERE 조건 검색 속도 개선, JOIN 성능 향상, ORDER BY, GROUP BY 최적화를 위해서 사용됩니다. 조회성능이 향상되며 대용량 데이터에서 효과가 크다는 장점이 있지만 저장 공간을 추가적으로 사용해야하며 과도한 인덱스는 오히려 성능을 저하할 수 있다는 단점이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (123,3,4,'JVM은 Class Loader, Runtime Data Area, Execution Engine, Garbage Collector로 구성되어 바이트코드를 해석·최적화해 실제 프로그램을 실행합니다. Java는 소스 코드가 자바 컴파일러에 의해(javac) 바이트코드로 컴파일되고 JVM에서 운영체제에 맞는 기계어로 변환되어 실행됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (124,3,5,'GC는 garbage collector의 약자로 JVM이 힙 영역에서 사용되지 않는 객체를 자동으로 제거해 메모리를 관리하는 기능입니다. 이로써 메모리 누수를 방지하고 개발자의 메모리 관리 부담 감소할 수 있어 안정적인 애플리케이션 실행이 가능합니다. gc root에서부터 참조할 수 있는 객체에 전부 mark를 하며 mark가 안된 객체에 한해서 객체들을 제거하고 메모리를 정리합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (125,3,6,'데이터 객체를 효율적으로 관리하고 사용하기 위해 java.util에서 제공하는 표준화된 클래스 및 인터페이스 집합입니다. 일관된 API를 제공하고 가변적인 저장공간을 사용할 수 있으며 API코드가 고도로 최적화되어있다는 장점이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (126,3,7,'리스트나 해시 같은 컬렉션 클래스나 메서드를 ''정의''할 때 타입을 고정하지 않고 사용할 때 구체적인 타입을 지정하는 기법으로 코드 재사용성을 높이고, 컴파일 시 타입 체크를 하여 형변환 에러를 방지하며, 데이터 타입을 동적이고 안전하게 관리할 수 있는 특징이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (127,3,9,'오버라이딩(Overriding)은 상속받은 메서드의 내용만 변경하는 것입니다. 매개변수의 타입과 순서, 리턴타입, 클래스명이 전부 다 같아야하며 자식 클래스에서 오버라이딩하는 메서드의 접근 제어자는 부모 클래스보다 더 좁게 설정할 수 없다는 특징이 있습니다.
오버로딩(Overloading)은 메서드의 이름은 같고 ''매개변수''의 유형과 개수가 다르도록 하는 것을 의미하며 리턴값만을 다르게 갖는 오버로딩은 작성할 수 없습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (128,3,11,'TLS(Transport Layer Security, 전송 계층 보안)는 인터넷상에서 데이터를 안전하게 전송하기 위해 데이터를 암호화하고 무결성을 보장하는 보안 프로토콜입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (129,3,15,'스레드 중 하나가 죽으면 프로세스 전체가 종료되는 주된 이유는 스레드들이 메모리(힙, 데이터, 코드 영역)와 자원을 공유하기 때문입니다. 하나의 스레드가 심각한 오류(예: 메모리 오염, Segfault)를 일으키면 해당 프로세스의 전체 메모리 공간이 더 이상 안전하지 않게 되어 운영체제가 프로세스 전체를 종료시킵니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (130,3,16,'병목현상(Bottleneck)은 전체 시스템의 성능이나 처리 속도가 가장 느린 하나의 구성 요소(병의 목 부분)에 의해 제한받는 현상을 의미합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (131,2,1,'먼저 브라우저는 DNS서버를 통해 도메인의 IP 주소를 찾아냅니다. 만약 캐시에 기록이 없으면 루트 서버부터 순차적으로 물어봐서 찾아옵니다.
IP를 획득하면 서버와 TCP 3-way handshake를 통해 연결을 수립합니다.
이때 HTTPS이므로 TLS 핸드셰이크를 통해 암호화키를 교환합니다.
연결이 완료되면 암호화된 HTTP 요청을 보내고 서버의 응답을 받아 브라우저가 화면에 렌더링합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (132,2,3,'인덱스는 책의 목차처럼 검색 성능을 높이기 위해 사용하는 기술입니다. B-Tree 구조를 통해 조회 속도를 획기적으로 줄일 수 있다는 장점이 있습니다.
하지만 저장공간을 추가로 차지하고 데이터 변경 시 인덱스도 재정렬해야 해서 쓰기 성능은 오히려 떨어질 수 있습니다.
그래서 변경이 적고 중복이 적은 컬럼에 사용하는 것이 좋습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (133,2,4,'JVM은 크게 클래스로더, 메모리 영역, 실행 엔진으로 구성됩니다.
클래스로더는 바이트코드를 메모리에 올리고, 메모리 영역은 메서드, 힙, 스택으로 나뉘며, 실행 엔진이 바이트코드를 실제로 실행합니다.
실행 흐름은 자바 코드를 컴파일러가 바이트코드로 변환하고 클래스로더가 JVM에 올리면 실행 엔진이 처리하는 순서입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (134,2,5,'GC는 힙 영역에서 사용하지 않는 객체를 자동으로 삭제해주는 프로세스입니다.
개발자가 직접 메모리를 해제하지 않아도 되기 때문에 메모리 누수를 방지하고 안정적인 애플리케이션 운영이 가능합니다.
동작 방식은 처음 생성된 객체는 Young 영역에 있다가 살아남으면 Old 영역으로 승격되는 구조입니다.
Old 영역이 가득 차서 Major GC가 발생하면 애플리케이션이 잠시 멈추는 Stop-the-world가 발생할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (135,3,28,'배열은 같은 타입의 데이터가 연속된 메모리 공간에 저장된 자료구조로 접근이 빠르지만 삽입/삭제가 비효율적이고, 링크드 리스크는 노드가 연결된 자료구조로 삽입/삭제는 빠르지만 순차탐색만 가능하다는 특징이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (136,3,29,'대칭키 암호화는 하나의 키로 암호화와 복호화를 모두 수행하며 속도가 빠르지만 키 전달중 탈취가 발생할 수 있다는 단점이 있습니다. 대표적인 예시로 AES 암호화 알고리즘이 있습니다. 비대칭 암호화는 속도는 느리지만 안전한 키 교환이 가능하며 기밀성/인증/부인 방지 기능을 제공한다는 장점이 있습니다. 대표적으로 RSA, DSA 알고리즘이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (137,3,30,'DI(Dependency Injection)는 필요한 객체를 직접 생성하지 않고 외부에서 주입받는 방식이고 IoC(Inversion of Control)는 객체 생성과 관리의 제어권이 Spring Container로 넘어가는 것입니다. 컴포넌트 스캔을 통해 Bean을 등록하고 의존성을 분석한 후 적절한 Bean을 찾아 주입하는 흐름으로 동작합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (138,2,6,'컬렉션 프레임워크는 다수의 데이터를 쉽고 효율적으로 처리할 수 있도록 표준화된 클래스의 집합입니다.
크게 List, Set, Map 3가지로 나뉩니다. List는 순서가 있고 중복을 허용하며 대표적으로 ArrayList가 있습니다. Set은 순서가 없고 중복을 허락하지 않으며 대표적으로 HashSet이 있습니다. Map은 Key와 Value의 쌍으로 데이터를 관리하며 HashMap이 대표적입니다.
List와 Set은 Collection 인터페이스를 상속받지만 Map은 구조상의 차이로 별도로 정의되어 있다는 점이 특징입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (139,3,31,'인터페이스는 기능의 명세만 정의한 설계도와 같습니다. 하나의 클래스는 여러 인터페이스를 구현하는 다중 구현이 가능합니다. 따라서 구현체 교체와 확장에 유리합니다. 반면 추상클래스는 공통 상태와 일부 구현을 포함할 수 있어 코드 재사용에 적합하지만 단일 상속만 가능합니다. 따라서 계층 구조를 표현할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (140,3,32,'클래스는 객체를 생성하기 위한 설계도이며 객체는 클래스에 의해 생성된 실제 인스턴스입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (141,3,24,'Minor GC는 young영역에서 동작하는 gc로 Major gc보다 자주 동작합니다.
Major gc는 old영역에서 동작하는 gc로 동작 시 stop-the-world가 발생합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (142,3,25,'살아있는 객체를 식별하기 위해 출발점으로 삼는 최상위 참조점으로 스택, 정적 필드 등 실행 중인 코드에서 직접 접근 가능한 객체들을 말함.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (143,3,26,'인터페이스 구현체는 인터페이스를 실제로 작동하는 코드인 클래스로 구체화한 것입니다. 대표적인 예시로 List인터페이스를 구현한 ArrayList, LinkedList 구현체등이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (144,3,27,'자식 클래스에서 부모 클래스의 메서드를 오버라이딩할 때, 반환 타입을 부모의 타입에서 자식의 타입(하위 타입)으로 더 구체적으로 변경할 수 있는 기능을 말합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (145,2,7,'데이터 타입을 클래스 내부가 아닌 외부에서 지정해주는 기법입니다.
가장 큰 장점은 컴파일 시점에 타입을 체크해서 런타임 에러를 방지할 수 있다는 점입니다.
또한 데이터를 꺼낼 때마다 형변환을 하지 않아도 되어 코드가 간결해집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (146,2,8,'어노테이션은 소스 코드에 메타데이터를 추가하여 컴파일러나 런타임에 정보를 제공하는 기능입니다. 주석과는 다르게 코드의 동작에 영향을 미칠 수 있습니다.

대표적으로 `@Override`처럼 컴파일러에게 문법 체크를 맡기는 용도로 사용됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (147,2,9,'오버로딩은 매개변수만 바꿔서 같은 이름의 메서드를 여러 개 만드는 것으로 컴파일 시점에 결정됩니다.
오버라이딩은 상속받은 메서드를 자식 클래스에서 재정의하는 것으로 런타임에 결정됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (148,3,33,'static은 객체가 아닌 클래스에 속하는 멤버로 모든 인스턴스가 공유합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (149,2,10,'도메인 이름을 IP주소로 변환해주는 시스템입니다.
사용자가 도메인을 입력하면 로컬 DNS에 IP를 물어봅니다 만약 존재하지 않으면 로컬 DNS가 루트 서버부터 차례대로 물어봐서 IP를 찾습니다.
쉽게 말해 전화번호부 같은 시스템입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (150,2,11,'인터넷통신을 암호화하는 프로토콜입니다. HandShake 과정을 통해 서로 신원을 확인하고 암호화키를 교환해서 안전하게 데이터를 주고받습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (151,2,12,'논리적인 IP 주소를 물리적인 Mac주소로 변환하는 프로토콜입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (152,2,13,'데이터를 받을 때 물리 계층부터 응용 계층까지 올라가면서 헤더를 하나씩 벗겨내며 데이터를 확인하는 과정입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (153,3,34,'자바의 원시 타입은 byte(1), boolean(1), short(2), char(2), int(4), float(4), double(8), long(8)이 있으며 각각 1~8바이트 크기를 가집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (154,3,35,'public, protected, default, private이 있으며 public은 어디서든 접근 가능하고 protected는 같은 패키지와 상속받은 곳에서 접근 가능하며 default는 같은 패키지에서만 접근 가능합니다. private은 같은 클래스 내부에서만 접근 가능합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (155,2,14,'코드 영역에는 실행할 명령어가 저장됩니다.
데이터 영역에는 전역변수와 정적변수가 저장됩니다.
힙 영역에는 new로 동적으로 생성한 객체가 저장됩니다.
스택 영역에는 지역변수와 매개변수가 저장됩니다.
레지스터에는 CPU가 현재 연산 중인 데이터가 저장됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (156,2,15,'스레드끼리는 메모리 공간을 공유하기 때문입니다.
예를 들어 한 스레드가 잘못된 메모리 주소에 접근해 NullPointerException 같은 에러가 발생하면 프로세스 전체가 강제 종료될 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (157,2,16,'전체 시스템 성능이 가장 느린 하나의 요소 때문에 저하되는 현상입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (158,2,17,'두 개 이상의 프로세스나 스레드가 공유 자원에 동시에 접근하여 접근 순서에 따라 결과가 달라지는 문제입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (159,2,18,'프로세스들은 메모리를 공유하지 못하므로 프로세스끼리 데이터를 주고 받기 위해 사용하는 통신 메커니즘 입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (160,2,19,'데이터의 중복이 적고 유니크한 값이 많을수록 선택도가 높습니다.
예시로는 주민등록번호가 있습니다');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (161,2,20,'옵티마이저는 SQL을 가장 빠르고 효율적으로 실행하기 위해 최적의 경로를 결정하는 DBMS의 핵심 엔진입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (162,2,21,'자바코드에서 C나 C++로 만들어진 라이브러리를 호출해서 사용할 수 있게 해주는 인터페이스 입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (163,2,22,'스택 영역은 지역 변수, 메서드 영역은 클래스와 Static 변수, 힙 영역은 new로 생성된 인스턴스가 저장됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (164,2,23,'처음 생성된 객체는 Young 영역에 있다가 GC에서 계속 살아남으면 Old영역으로 이동하는데 이를 승격이라고 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (165,2,24,'Minor GC는 Young 영역이 꽉 찼을 때 발생하고 속도가 빠르고 빈번합니다.
Major GC는 Old 영역이 꽉 찼을 때 발생하고 속도가 느리고 시스템이 멈출(Stop-the-world) 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (166,3,36,'객체지향은 현실 세계의 개념을 객체 단위로 모델링하여 데이터와 행위를 하나로 묶는 프로그래밍 패러다임(인식체계, 틀)입니다. 4대 특징에는 캡슐화, 상속, 다형성, 추상화가 있습니다. 캡슐화는 내부 구현을 보호하고 외부로 공개된 메서드를 통해서만 수정이 가능하도록 하는 것입니다. 상속은 기존 클래스의 속성과 동작을 물려받아 새로운 클래스를 확장하는 개념으로 계층 구조를 표현할 수 있습니다. 다형성은 동일한 인터페이스로 다양한 객체를 처리할 수 있다는 특징이며 추상화는 공통적인 속성과 동작만을 정의하고 세부 구현은 감추어 복잡성을 줄이는 개념입니다. 이를 통해 유지보수성과 확장성이 높은 구조를 설계할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (167,2,25,'GC가 살아있는 객체인지 판단하는 시작점입니다. 실행 중인 스레드의 지역변수나 Static 변수 등이 해당됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (168,2,26,'인터페이스는 설계도이고 구현체는 그 기능을 실제로 코드로 만든 클래스입니다.
이렇게 분리하면 나중에 LinkedList같은 다른 구현체로 갈아끼우기 쉽습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (169,2,27,'오버라이딩할 때, 부모 메서드의 반환 타입보다 더 구체적인 자식 타입으로 바꿔서 반환할 수 있는 기능입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (170,2,28,'가장 큰 차이는 메모리 구조입니다. 배열은 연속된 공간에 저장되어 인덱스로 조회는 빠르지만 중간에 데이터를 넣거나 뺄 때는 뒤의 데이터를 다 밀어야 해서 느립니다.<br>
반면 링크드 리스트는 데이터가 흩어져 있고 주소로 연결되어 있어 조회는 처음부터 찾아가야 해서 느리지만 삽입과 삭제는 주소만 바꾸면 돼서 빠릅니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (171,2,29,'대칭키는 암호화와 복호화에 같은 키를 씁니다. 연산 속도가 빠르지만 상대방에게 키를 안전하게 전달하는 게 어렵습니다.<br> 비대칭키는 공개키와 개인키, 두 개의 키를 씁니다. 공개키로 잠그고 개인키로 여는 방식이라 키 관리는 안전하지만 연산 과정이 복잡해 속도가 느리다는 단점이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (172,3,37,'객체가 자신이 필요로 하는 의존 객체를 직접 생성하지 않고, 외부에서 주입받기 때문입니다. 이로 인해 구체적인 클래스에 의존하지 않고 인터페이스에 의존하게 되어 코드의 유연성과 유지보수성이 크게 향상됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (173,3,38,'클래스 로더(Class Loader)에 의해 클래스가 처음 사용될 때 Static 영역(Method Area)에 단 한 번 로드되어, 인스턴스(객체) 생성 여부와 무관하게 프로그램이 종료될 때까지 메모리에 고정(static)되기 때문입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (174,3,39,'JPA 영속성 컨텍스트는 애플리케이션과 DB 사이에서 객체를 관리하는 계층으로, 크게 5가지 이점이 있습니다.<br>
(1차 캐시) 같은 트랜잭션 내에서 ID가 같은 엔티티는 메모리에서 바로 조회하여 **DB 접근 횟수를 줄입**니다.<br>
(동일성 보장) == 비교 시 같은 객체임을 보장하여 **데이터 정합성을 유지**합니다.<br>
(쓰기 지연) 변경 사항을 즉시 DB에 보내지 않고 모았다가 커밋 시점에 한 번에 반영하여 **네트워크 비용을 줄입**니다.<br>
(변경 감지) 객체의 값만 바꾸면 커밋 시점에 자동으로 Update SQL이 생성되어, **수정 쿼리를 직접 작성할 필요가 없습**니다.<br>
(지연 로딩) 연관된 객체를 실제 사용하는 시점에 가져오도록 프록시를 활용해 **불필요한 데이터 조회를 방지**합니다.<br>');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (175,3,40,'tcp는 인터넷상에서 컴퓨터들간에 데이터를 안전하게 유실없이 주고받을 수 있도록 하는 연결지향형 프로토콜입니다. 따라서 데이터를 전송하기 전에 3-way handshake를 통해서 안정적으로 데이터를 보낼 수 있는 상태를 만든 후 데이터를 전송하게됩니다. 만약 패킷이 중간에 유실이 된다면 재요청하고 순서를 다시 맞추어 높은 신뢰도를 보장합니다. 반면 udp는 비연결형 데이터그램 프로토콜로 데이터의 유실이 있을 수 있지만 속도가 빨라서 온라인 게임이나 DNS 또는 온라인 스트리밍등에 주로 사용됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (176,3,41,'컨텍스트 스위칭은 CPU가 실행 중인 프로세스나 스레드를 변경하는 과정이며, 이때 레지스터 상태 저장과 복원이 발생해 오버헤드가 발생합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (177,3,42,'SOLID는 객체 지향 설계 원칙으로 하나의 클래스는 하나의 책임만 져야하며 기능 추가시 기존 코드에 변화 없이 쉽게 확장이 가능해야하고 자식은 부모를 대체 가능해야한다는 것입니다. 또한 클래스는 불필요한 인터페이스 구현이 없어야 하며 구체화된 클래스가 아닌 추상화에 의존해야한다는 내용입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (178,3,43,'동일성은 객체의 참조값인 메모리 주소를 비교하는 것이고, 동등성은 equals()를 통해 객체의 실제적인 값을 비교하는 것입니다.
```
new String("a") == new String("a")  // false
.equals()  // true
```');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (179,3,44,'원시타입은 실제 값을 스택 메모리에 저장하며 참조타입은 실제 값은 힙 영역에 저장하고 데이터의 주소값을 스택에 저장합니다. 따라서 원시타입은 null을 가질 수 없으며 참조타입에는 null이 저장 가능합니다. 또한 참조값은 주소 탐색이 필요하므로 원시타입보다 성능이 떨어집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (180,3,45,'String은 불변 객체로 문자열 상수 풀과 보안, 해시 안정성을 위해 설계되었습니다.
문자열을 많이 변경하는 경우에는 가변 객체인 StringBuilder를 사용하며, 멀티스레드 환경에서 동기화가 필요하다면 StringBuffer를 사용할 수 있습니다. 다만 일반적으로는 성능상 StringBuilder를 더 많이 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (181,3,46,'Checked Exception은 컴파일 시 예외 처리를 강제하며, 복구 가능성이 있는 예외를 표현하기 위해 사용됩니다.
반면 Unchecked Exception은 RuntimeException을 상속하며, 주로 개발자의 논리적 오류를 나타냅니다.
스프링의 @Transactional은 기본적으로 RuntimeException 발생 시 롤백하며, Checked Exception은 명시적으로 rollbackFor 옵션을 설정해야 롤백됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (182,3,47,'Java 8은 람다 표현식과 Stream API를 통해 함수형 프로그래밍을 도입했고, Optional을 통해 null 안정성을 개선했으며, 인터페이스 내부에 default method를 추가하고 새로운 날짜 API를 추가해 기존 Java의 한계를 보완한 중요한 버전입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (183,3,48,'TCP에서 시퀀스 번호(Sequence Number, Seq)는 전송되는 데이터의 순서를 보장하기 위해 각 세그먼트(패킷)에 부여하는 고유 번호이며, ACK(Acknowledgment Number, 응답 번호)는 수신자가 데이터를 잘 받았음을 확인하고 다음에 받을 데이터를 알리는 번호입니다. 이 둘은 TCP의 핵심인 데이터 순서 재정렬, 오류 복구, 신뢰성 있는 통신을 가능하게 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (184,3,50,'트랜잭션은 하나의 논리적 작업 단위로, 모두 성공하거나 모두 실패해야 하는 작업 묶음입니다. ACID 특성을 통해 데이터의 무결성과 일관성을 보장합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (185,3,49,'Process Control Block (프로세스 제어 블록)의 약자로, 운영체제가 프로세스를 관리하기 위해 프로세스의 핵심 정보를 저장하는 데이터 구조입니다. 입니다. 프로세스 생성 시 생성되어 메모리(커널 스택)에 저장되며, 문맥 교환(Context Switching) 시 프로세스 상태를 저장/복구하는 데 사용됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (186,2,30,'**IoC(제어의 역전)** 는 스프링컨테이너가 객체의 생성과 생명주기를 관리하는 것이고
**DI(의존성 주입)** 는 그 객체를 필요한 곳에 주입해주는 기술입니다.
애플리케이션이 시작될 때 어노테이션을 읽어 빈으로 등록해두고 필요한곳에 주입해주는 흐름으로 동작합니다.
덕분에 개발자가 직접 new로 객체를 생성할 필요가 없어 객체 간 결합도를 낮출 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (187,2,31,'둘은 사용하는 목적이 다릅니다.
추상 클래스는 부모의 기능을 물려받아 기능을 확장(상속)하는 데 목적이 있고, 
인터페이스는 어떤 객체든 동일한 동작을 하도록 보장하는 데 목적이 있습니다.

(여유되면)자바에서 클래스는 다중 상속이 안 되지만, 인터페이스는 여러 개를 구현할 수 있다는 차이도 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (188,2,32,'클래스는 객체를 만들기 위한 설계도 즉 틀입니다. 객체는 그 설계도를 바탕으로 실제 메모리에 생성된 실체(Instance)입니다');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (189,2,33,'static은 고정된이라는 뜻으로 객체 생성 없이 클래스가 로드될 때 메모리에 딱 한 번 생성되는 것을 말합니다.
프로그램 종료 시까지 메모리에 남아있기 때문에 모든 객체에서 공통으로 공유하는 데이터나 유틸리티 메서드에 주로 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (190,2,34,'자바에는 총 8가지 원시 타입이 있습니다.
크기가 작은순서부터 1바이트는 byte, boolean, 2바이트는 char, short 4바이트는 int, float, 8바이트는 long, double이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (191,2,35,'접근 범위가 넓은 순서대로 4가지가 있습니다. 어디서든 접근 가능한 public, 같은 패키지거나 상속받은 자식 클래스에서 접근 가능한 protected, 아무것도 안 썼을 때 같은 패키지에서만 접근 가능한 default, 그리고 해당 클래스 내부에서만 접근할 수 있는 private이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (192,2,36,'- 첫째, 상속은 부모 클래스의 기능을 자식이 물려받아 재사용하는 것입니다.
- 둘째, 추상화는 불필요한 정보는 숨기고 중요한 특징만 뽑아내는 것입니다.
- 셋째, 캡슐화는 데이터와 기능을 하나로 묶고 외부 접근을 제한하는 것입니다.
- 넷째, 다형성은 같은 이름의 메서드가 상황에 따라 다르게 동작하는 것으로 오버로딩과 오버라이딩이 대표적입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (193,2,37,'DI를 사용하지 않으면 객체 안에서 직접 new로 객체를 생성해야 해서 나중에 객체를 교체할 때 코드를 다 수정해야 함
DI는 외부에서 주입받기 때문에 객체가 교체되어도 기존 코드를 수정할 필요가 없어 결합도가 낮음');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (194,2,38,'static 멤버는 객체가 아니라 클래스에 소속되기 때문
가비지 컬렉터가 관리하는 힙 영역이 아니라 스태틱 영역에 할당되어 GC가 지우지 않기 때문에 프로그램 종료 시까지 유지됨');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (195,3,51,'List는 순서를 유지하고 중복을 허용하는 컬렉션인 반면, Set은 일반적으로 순서를 보장하지 않고 중복을 허용하지 않는 컬렉션입니다. Set의 경우 순서를 유지하고자 한다면 LinkedHashSet을 사용할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (196,3,52,'단방향 암호화는 복호화가 불가능한 해시 기반 암호화 방식으로, 주로 비밀번호 저장에 사용됩니다. 대표적으로 SHA-256알고리즘이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (197,3,53,'try-with-resources는 AutoCloseable을 구현한 자원을 자동으로 해제해주는 구문입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (198,3,54,'강한 결합이란 구체 클래스에 직접 의존하여, 구현 변경 시 사용하는 코드도 함께 수정해야 하는 상태이며 느슨한 결합이란 인터페이스에 의존하고 객체 생성을 외부로 분리하여, 구현 변경 시 사용하는 코드 수정이 필요 없는 구조입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (199,3,55,'직렬화는 객체를 바이트 스트림으로 변환하는 것이고, 역직렬화는 이를 다시 객체로 복원하는 과정입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (200,3,56,'동시성 이슈는 여러 스레드가 공유 자원에 동시에 접근할 때 데이터의 일관성과 정합성이 깨지는 현상으로 synchronized나 Lock, AtomicInteger 등을 통해 해결할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (201,3,57,'Mutable 객체는 상태 변경이 가능하고, Immutable 객체는 생성 이후 상태 변경이 불가능합니다. Mutable객체는 데이터 수정 시 새로운 객체를 생성하지 않아 메모리 overhead가 적고 효율적입니다. Immutable 객체는 안정적이지만 변경이 잦은 경우에는 메모리 사용량이 증가할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (202,3,58,'null은 NullPointerException을 유발할 수 있기 때문에 Optional 사용, 명시적 null 체크, @NonNull 어노테이션 등을 통해 안전하게 다루는 것이 중요합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (203,3,59,'Spring Bean은 Spring IoC 컨테이너가 생성하고 관리하는 객체입니다. 개발자가 직접 new로 생성하는 것이 아니라, 컨테이너가 객체의 생성, 의존성 주입, 생명주기 관리를 담당합니다. 기본적으로 싱글톤으로 관리되며, @Component나 @Bean 등을 통해 등록할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (204,3,60,'먼저 BeanDefinition이라는 메타정보가 생성됩니다. 이후 Reflection으로 객체가 생성되고, 의존성 주입이 이루어집니다. 그 다음 (@PostConstruct 같은) 초기화 메서드가 실행되며, 필요하다면 (BeanPostProcessor를 통해) 프록시가 생성됩니다. 컨테이너 종료 시에는 소멸 콜백이 호출됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (205,3,61,'Spring Bean Scope는 Bean의 생명 범위를 의미합니다. 기본은 Singleton으로 컨테이너당 하나의 인스턴스를 공유합니다. Prototype은 요청할 때마다 새로운 객체를 생성하며, Web 환경에서는 request, session, application scope도 지원합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (206,3,62,'IoC 컨테이너는 객체 생성과 의존성 주입을 담당하며, Bean의 생명주기와 싱글톤 관리, AOP 적용까지 수행합니다. 이를 통해 객체 간 결합도를 낮추고 유지보수성을 향상시킵니다. <br>
* AOP(Aspect-Oriented Programming, 관점 지향 프로그래밍) : 로깅,트랜잭션,보안 등 여러 클래스에서 공통적으로 쓰이는 부가 기능(횡단 관심사)을 핵심 비즈니스 로직에서 분리하여 모듈화하는 프로그래밍 패러다임');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (207,3,63,'트랜잭션 전파는 트랜잭션 동작 중 다른 트랜잭션을 호출할 때 호출된 트랜잭션이 기존 트랜잭션과 어떤 관계를 맺을지 결정하는 설정입니다. 기본값인 REQUIRED는 기존 트랜잭션에 참여하고 없으면 새로 생성합니다. REQUIRES_NEW는 항상 새로운 트랜잭션을 생성하며, MANDATORY는 기존 트랜잭션이 반드시 필요합니다. 그 외에는 SUPPORTS, NOT SUPPORTED, NESTED, NEVER가 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (208,3,64,'TCP의 3-way handshake는 데이터 전송 전 클라이언트와 서버가 연결을 수립하는 과정입니다. <br>
4-way handshake는 통신 종료 후 연결을 해제하는 과정입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (209,3,65,'JRE는 자바 프로그램 실행을 위한 환경이며 JVM과 라이브러리를 포함합니다. JDK는 JRE에 컴파일러를 포함한 개발 도구가 추가된 것으로, 자바 개발을 위해 필요합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (210,3,105,'사용자 입력값에 악의적인 SQL 구문을 삽입해 데이터베이스를 비정상적으로 조작하는 공격 기법입니다.
가장 효과적인 방어 방법은 Prepared Statement를 사용하는 것으로, SQL 구조를 먼저 컴파일하고 사용자 입력을 데이터로만 바인딩해 입력값이 SQL 구조에 영향을 줄 수 없게 합니다. JPA를 사용하면 내부적으로 Prepared Statement를 사용하므로 기본적으로 방어됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (211,3,104,'JWT와 OAuth는 서로 다른 레이어의 개념으로 JWT는 인증 정보를 담는 토큰의 형식이고, OAuth는 제3자 앱에 권한을 위임하는 프로토콜입니다. 실무에서는 OAuth로 소셜 로그인 처리 후 사용자 정보를 확인하고, 이후 서비스 내부에서는 JWT를 발급해 인증하는 방식으로 두 가지를 조합해서 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (212,3,103,'OAuth는비밀번호를 공유하지 않고도, 특정 서비스(Google, Kakao 등)의 데이터에 접근할 수 있는 ''권한''을 안전하게 위임받기 위한 표준 프로토콜입니다. 대표적으로 소셜로그인에서 사용됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (213,3,102,'Tree는 계층적 구조를 표현하는 비선형 자료구조입니다. 노드(Node)와 간선(Edge)으로 구성되며 사이클이 없습니다.
Binary Tree는 각 노드가 최대 2개의 자식을 가지는 트리입니다. BST는 이진트리(Binary Tree)에 왼쪽 자식이 부모보다 작고 오른쪽 자식이 크다는 조건을 추가해 평균 O(log n) 탐색이 가능합니다. 하지만 삽입 순서에 따라 편향 트리가 되면 O(n)으로 성능이 저하됩니다. AVL Tree는 모든 노드의 좌우 서브트리 높이 차이를 최대 1로 유지하는 자가 균형 BST로, 회전 연산을 통해 항상 O(log n)을 보장합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (214,3,101,'Heap은 완전 이진 트리 기반의 자료구조로 삽입과 삭제는 O(log n)이고 Min Heap, Max Heap 각각의 최솟값/최댓값 조회는 O(1)입니다. Priority Queue는 Heap을 내부 구현으로 사용하며, FIFO가 아닌 우선순위 순서로 데이터를 꺼내는 자료구조입니다.
_(다익스트라 알고리즘, CPU 스케줄링 등에 활용됩니다.)_');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (215,3,100,'Stack은 LIFO(Last In First Out) 구조로 마지막에 삽입한 데이터가 먼저 삭제됩니다. 함수 호출 스택, 괄호 유효성 검사, 브라우저 뒤로가기 등에 사용됩니다. Queue는 FIFO(First In First Out) 구조로 먼저 삽입한 데이터가 먼저 삭제됩니다. BFS, 프린터 대기열, Kafka 같은 메시지 큐에 사용됩니다. 두 자료구조 모두 삽입과 삭제가 O(1)입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (216,3,99,'JOIN은 두 개 이상의 테이블을 특정 조건으로 결합하는 연산입니다. JOIN 성능을 위해 조인 조건 컬럼에 인덱스를 설정해야 하고, 작은 테이블을 기준으로 WHERE 조건으로 먼저 데이터를 줄인 후 JOIN하는 것이 좋습니다.<br>
_*(조인 순서는 성능에 큰 영향을 미치므로 "가장 적은 데이터"를 만들어내는 필터링을 조인보다 먼저 처리하는 것이 원칙)_');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (217,3,98,'정규화는 데이터 중복을 제거하고 이상 현상(Anomaly)을 방지하기 위해 테이블을 올바른 구조로 분리하는 과정입니다. 다만 정규화가 지나치면 JOIN이 많아져 성능이 저하될 수 있으므로, 실무에서는 조회 성능이 중요한 경우 반정규화를 함께 고려합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (218,3,97,'트랜잭션 격리 수준은 동시에 실행되는 트랜잭션 간의 데이터 가시성을 제어하는 수준입니다. 낮은 순서로 READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE 4단계가 있습니다. 격리 수준이 낮을수록 Dirty Read, Non-Repeatable Read, Phantom Read와 같은 문제가 발생할 수 있고, 높을수록 동시성 성능이 낮아지는 문제가 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (219,3,96,'Spring Boot는 SpringApplication.run() 호출을 통해 내장 WAS를 실행하고, 자동 설정(Auto-configuration)과 컴포넌트 스캔을 거쳐 IoC 컨테이너를 초기화하여 애플리케이션을 구동합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (220,3,95,'웹 서버는 HTML, 이미지 등 정적 콘텐츠를 처리하는 HTTP 기반 서버(Apache, Nginx)이며, WAS(Web Application Server)는 DB 조회, 로직 처리 등 동적 콘텐츠를 생성하는 서버(Tomcat, Jeus)입니다. 보통 웹 서버가 앞단에서 정적 파일을 처리하고, 복잡한 동적 요청을 WAS에 넘기는 구조로 부하를 분산합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (221,3,94,'세션 방식은 서버 메모리를 사용하기 때문에 동시 접속자가 늘어나면 서버에 부하가 커집니다. 저희 서비스의 메신저 기능이 있어 접속자가 많을 경우를 염두해 상대적으로 서버 부하 관리에 유리한 JWT 방식을 사용하게 되었습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (222,3,93,'생성자 주입을 권장하는 이유는 final 키워드를 사용해 불변성을 보장할 수 있으며 순환 참조를 방지할 수 있고 (Spring 컨텍스트 없이 생성자로 Mock을 바로 주입할 수 있어) 단위 테스트가 용이하기 때문입니다. 또한 객체 생성 시점에 모든 의존성이 반드시 주입되어야 하므로 필수 의존성이 명확해지고 NullPointerException을 방지할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (223,3,91,'Interceptor는 Spring 컨텍스트 안에 있어서 예외가 발생하면 DispatcherServlet이 잡아 @ControllerAdvice로 처리할 수 있습니다. 반면 Filter는 Spring 컨텍스트 바깥 Tomcat 레벨에서 동작하므로 @ControllerAdvice가 동작하지 않습니다. Filter의 예외는 세 가지 방법으로 처리할 수 있는데, Filter 내부에서 직접 HttpServletResponse에 응답을 작성하거나, 예외 처리 전담 Filter를 체인 맨 앞에 배치하거나, HandlerExceptionResolver를 주입받아 Spring의 예외 처리 체계에 위임하는 방법이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (224,3,90,'Request별로 생성해주어야 하는 Java Servlet과 다르게 Spring은 DispatcherServlet 하나만 등록해 모든 요청을 받는 프론트 컨트롤러 패턴으로 구현되어 있습니다. DispatcherServlet은 HandlerMapping, HandlerAdapter, ViewResolver를 두어 요청을 적절한 Controller에 위임하고 응답을 처리합니다. 이렇게 하나의 객체에서 모든 요청을 먼저 처리하기 때문에 재사용성이 좋고 관리가 용이합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (225,3,89,'스프링 프레임워크는 기본적으로 POJO기반의 모든 Bean을 Singleton Scope로 관리하기 때문입니다. 따라서 Spring 컨테이너가 시작될 때 딱 1개만 생성하고, 모든 요청이 그 1개의 인스턴스를 공유하게됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (226,3,88,'멀티스레드 프로그래밍은 하나의 프로세스 안에서 여러 스레드가 동시에 실행되도록 하는 방식입니다. CPU를 효율적으로 활용해 성능과 응답성을 높일 수 있지만, 여러 스레드가 공유 자원에 동시 접근할 때 경쟁 조건이나 교착 상태 같은 문제가 발생할 수 있습니다. 이를 해결하기 위해 synchronized, AtomicInteger, lock과 같은 동기화 메커니즘을 사용합니다.<br>
_(Spring에서는 Thread Pool을 통해 스레드를 미리 생성해두고 재사용하여 생성/소멸 비용을 줄입니다.)_');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (227,3,87,'HTTP는 데이터를 평문으로 전송하는 프로토콜이고, HTTPS는 HTTP에 TLS 암호화를 추가한 프로토콜입니다. HTTPS는 통신 전 SSL Handshake를 통해 암호화 키를 교환하는데, 비대칭키(공개키/개인키)로 대칭키를 안전하게 전달하고 이후 실제 통신은 빠른 대칭키로 처리합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (228,3,86,'깊은 복사는 객체와 내부의 모든 중첩 객체까지 새롭게 생성해 완전히 독립적인 복사본을 만듭니다. 반면, 얕은 복사는 객체의 참조값(메모리 주소)만 복사해 원본과 복사본이 같은 객체를 가리키므로, 한쪽을 수정하면 다른 쪽도 영향을 받습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (229,3,85,'N+1 문제는 한 번의 쿼리로 N개의 엔티티를 조회했으나, 각 엔티티의 연관 데이터를 가져오기 위해 N번의 추가 쿼리가 발생하는 성능 문제입니다. 주로 LAZY 로딩 상황에서 연관 엔티티에 접근할 때 발생합니다. 해결 방법으로는 JPQL의 Fetch Join으로 한 번에 조회하거나, @BatchSize를 설정해 조회하는 방법이 있습니다.<br>
_(컬렉션 조회 시 Fetch Join은 페이징이 불가능하므로, 실무에서는 Batch Size 설정을 권장합니다.)_');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (230,3,84,'JPA를 사용하는 이유는 ORM을 통해 객체와 관계형 DB 간의 패러다임 불일치를 해결해주며 SQL 자동 생성으로 반복 작업이 줄어 생산성이 향상됩니다. Dialect 설정만 바꾸면 DB 종류에 독립적인 코드 작성이 가능하며 영속성 컨텍스트가 제공하는 1차 캐시와 변경 감지로 성능 최적화와 편리한 엔티티 관리가 가능합니다. <br>
_(다만 연관관계 조회 시 N+1 문제가 발생할 수 있으므로 Fetch Join이나 Batch Size로 해결)_');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (231,3,83,'JWT는 Header, Payload, Signature 세 부분으로 구성된 토큰 기반 인증 방식입니다. 서버가 상태를 저장하지 않아도 되는 Stateless 구조라 서버 확장에 유리하고 DB 조회가 불필요합니다. 다만 한번 발급된 토큰은 만료 전까지 무효화하기 어렵기 때문에, 수명이 짧은 AccessToken과 수명이 긴 RefreshToken을 함께 사용하는 방식으로 보완합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (232,3,82,'해시 함수는 임의의 데이터를 고정된 크기의 해시값으로 변환하는 함수이고, 해시 테이블은 이 해시값을 배열의 인덱스로 사용해 키-값 쌍을 저장하는 자료구조입니다. 평균 O(1)으로 빠른 조회 성능이 장점이지만, 서로 다른 키가 같은 해시값을 갖는 해시 충돌이 발생할 수 있습니다. 이러한 문제는 chaining이나 open addressing으로 해결할 수 있습니다.<br>
_(Java 8부터는 충돌이 일정 수 이상이면 연결 리스트를 레드-블랙 트리로 전환해 최악의 경우를 O(n)에서 O(log n)으로 개선합니다.")_');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (233,3,81,'POJO는 특정 프레임워크나 기술에 종속되지 않은 순수 Java 객체입니다. Spring에서는 어노테이션이 붙은 클래스들이 모두 POJO가 될 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (234,3,80,'CORS는 브라우저의 동일 출처 정책으로 인해 다른 출처의 API 요청이 차단되는 현상입니다. Spring에서는 세 가지 방법으로 해결할 수 있는데, 컨트롤러 단위에서는 @CrossOrigin를 이용할 수 있고 전역적인 설정은 addCorsMappings을 override해서 사용할 수 있습니다. Spring Security 사용 시에는 SecurityFilterChain을 빈으로 등록하여 사용할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (235,3,79,'Servlet Filter는 Servlet 컨테이너 레벨(DispatcherServlet 이전)에서 동작해 Spring과 무관하게 모든 요청을 처리하며 Request/Response 객체 자체를 변경할 수 있습니다. 반면 Spring Interceptor는 Spring 컨테이너 안에서 DispatcherServlet 이후에 동작하므로 Spring Bean 주입이 자유롭고 (preHandle, postHandle, afterCompletion으로) 세밀한 제어가 가능합니다. (따라서 인코딩이나 CORS처럼 서블릿 수준의 공통 처리는 Filter를, 인증/인가나 로깅처럼 Spring의 기능이 필요한 공통 처리는 Interceptor를 사용합니다.)');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (236,3,78,'프론트 컨트롤러 패턴은 모든 클라이언트 요청을 단일 진입점에서 받아 공통 처리(인증, 로깅 등)를 수행한 뒤 적절한 핸들러로 위임하는 패턴입니다. Spring MVC에서는 DispatcherServlet이 이 역할을 담당합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (237,3,77,'순수 WebSocket을 사용할 경우 메시지 형식과 구독, 브로드캐스트 구조를 직접 설계해야 하므로 복잡도가 증가합니다. STOMP를 사용하면 목적지 기반 구독 모델과 브로커 개념이 명확해지고, Spring에서는 STOMP를 지원하여 @MessageMapping, @SendTo 같은 어노테이션을 통해 MVC와 유사한 방식으로 메시지를 처리할 수 있고, 파싱 기능도 제공하기 때문에 유지보수성과 확장성이 좋아진다고 판단하여 WebSocket 위에 STOMP를 적용했습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (238,3,76,'화면에 사용자 이름이나 ID를 보여주려면 토큰 정보를 열어봐야 하는데 httpOnly 쿠키에 넣으면 자바스크립트가 접근할 수 없어 사용이 불가능합니다. 그래서 헤더 방식을 사용했고 대신 XSS 위험을 줄이기 위해 유효기간을 짧게 설정했습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (239,3,75,'Wrapper 클래스는 기본형 데이터를 객체로 감싼 클래스이며, 컬렉션 사용, 제네릭 적용, null 표현 등을 위해 사용됩니다. 자바는 오토박싱과 언박싱을 통해 자동 변환을 지원합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (240,3,74,'final은 최종적인 상태를 설정하고 변경을 제한합니다. 변수, 메서드, 클래스에 사용하여 재할당, 오버라이딩, 상속을 금지하여 코드의 안정성과 불변성을 보장합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (241,3,73,'트랜잭션의 4대 특징으로 작업은 모두 성공하거나 모두 실패해야하며 db제약 조건을 위반하면 안되며 동시에 동작하는 두 트랜잭션은 독립적이어야하고 커밋된 데이터는 영구적으로 유지되어야한다는 것입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (242,3,72,'동기는 작업 완료까지 기다리는 방식이고, 비동기는 결과를 기다리지 않고 다음 작업을 수행하는 방식입니다. <br>
동기 방식은 코드 흐름이 직관적이고 이해하기 쉽다는 장점이 있지만, 작업 시간이 길어질 경우 전체 처리 속도가 느려질 수 있습니다.
반면 비동기 방식은 자원을 효율적으로 활용할 수 있어 처리량을 높일 수 있지만, 흐름 제어가 복잡해질 수 있다는 단점이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (243,3,71,'DispatcherServlet은 Spring MVC의 프론트 컨트롤러로, 모든 HTTP 요청을 받아 HandlerMapping을 통해 적절한 컨트롤러를 찾고, HandlerAdapter를 통해 실행한 뒤 ViewResolver를 거쳐 응답을 반환합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (244,3,70,'Autowiring은 @Autowired 어노테이션이 붙은 지점에 스프링 컨테이너가 Bean을 생성한 뒤 타입을 기준으로 의존성을 자동 주입하는 과정이며, 동일 타입을 우선 비교하고 타입이 여러개이면 이름을 비교한 후 그래도 모호할 경우@Qualifier나 @Primary를 통해 명시적으로 지정할 수 있습니다. 그래도 여전히 모호하면 예외를 발생시킵니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (245,3,69,'DI는 객체의 의존성을 외부에서 주입하는 방식이며, 생성자 주입, 필드 주입, Setter 주입이 있습니다. 생성자 주입은 불변성을 보장하고 테스트가 용이하여 가장 권장됩니다. 필드 주입은 간편하지만 순환 참조가 발생할 수 있고 테스트가 어렵다는 단점이 있습니다. setter 주입은 선택적 의존이 가능하지만 객체 생성 후 주입이 이루어지기 때문에 불완전한 상태로 존재할 가능성이 있다는 단점이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (246,3,68,'웹소켓(WebSocket) 외에도 실시간 통신을 위한 다양한 방식이 있으며, 대표적으로 SSE(Server-Sent Events), 롱 폴링(Long Polling), 웹트릭(WebRTC) 등이 있습니다. 서버에서 클라이언트로의 단방향 데이터 전송이 필요하면 SSE를, 대규모 데이터 방송이 필요하면 롱 폴링을, P2P 영상/음성 통신은 웹트릭을 주로 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (247,3,67,'http는 요청-응답 구조라서 실시간으로 오는 메시지를 확인하려면 폴링을 해야합니다. 웹소켓은 한번 연결되면 양방향 통신이 가능하기 때문에 채팅처럼 실시간으로 서버에서 클라이언트로 푸시가 필요한 기능은 웹소켓이 더 적합하다고 판단했습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (248,3,66,'보안과 편의성을 위해서 나누어서 사용했습니다. 액세스 토큰은 유효기간을 길게 잡으면 탈취 시 위험하고, 짧게 잡으면 사용자가 계속 로그인을 해야해서 불편함을 느낄 수 있습니다. 그래서 액세스 토큰은 유효기간을 짧게 하여 보안을 챙기고 리프레시 토큰을 통해 자동으로 로그인이 유지되게 하여 사용자 경험을 높였습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (249,3,12,'논리적인 IP 주소를 기반으로 실제 장치의 물리적인 MAC 주소를 찾아내어 연결해 주는 네트워크 프로토콜입니다');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (250,3,22,'Runtime Data Area :
Method Area: 클래스 정보
Heap: 객체 저장
Stack: 메서드 호출, 지역 변수, PC Register, Native Method Stack');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (251,3,21,'자바 가상 머신(JVM) 위에서 실행되는 자바 코드가 C, C++, 어셈블리 등 네이티브 언어로 작성된 애플리케이션 및 라이브러리와 상호작용(호출)할 수 있게 해주는 인터페이스 프레임워크입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (252,3,20,'DB(데이터베이스)에서 옵티마이저(Optimizer)는 사용자가 작성한 SQL 쿼리를 가장 빠르고 효율적으로 처리할 수 있도록 최적의 경로(실행 계획, Execution Plan)를 수립하는 핵심 엔진입니다. 테이블의 통계 정보를 바탕으로 어떤 인덱스를 쓸지, 어떤 순서로 데이터를 읽을지 결정하여 시스템 리소스(I/O, CPU, 메모리)를 최소화합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (253,3,23,'가비지 컬렉션(GC)은 JVM의 힙(Heap) 메모리에서 더 이상 참조되지 않는 객체(가비지)를 찾아 자동으로 해제하는 프로세스입니다. 힙은 효율적인 관리를 위해 크게 Young Generation(신규 객체)과 Old Generation(장수 객체)으로 나뉘며, GC는 Minor GC(Young)와 Major/Full GC(Old)로 나뉘어 동작합니다. Minor GC에서 살아남아 설정된 Age(나이) 임계치에 도달한 객체가 Young 영역에서 Old 영역으로 옮겨지는 ''승격(Promotion)'' 과정이 발생합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (254,3,14,'코드에는 실행 명령어가, 데이터에는 전역·정적 변수가, 힙에는 동적 할당된 객체가 저장되며, 스택에는 지역 변수와 함수 호출 정보가, 레지스터에는 CPU의 현재 작업 상태와 연산 데이터가 저장됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (255,3,17,'두 개 이상의 프로세스나 스레드가 공유 자원에 동시에 접근하여 변경을 시도할 때, 접근 순서에 따라 결과가 예상치 못하게 달라지는 데이터 불일치 문제입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (256,3,18,'독립된 프로세스들이 데이터를 주고받으며 협력할 수 있도록 운영체제가 제공하는 통신 기법입니다. 메모리가 분리되어 있어 직접 공유가 불가능한 프로세스 간에 공유 메모리 또는 메시지 전달 방식을 통해 통신하며, 주요 방식으로는 파이프, 소켓, 세마포어 등이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (257,3,19,'서로 다른 값을 갖는 정도를 나타내며 상대적인 개념입니다. 예를 들면 주민등록 번호가 이름보다 선택도가 높다고 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (258,3,10,'DNS는 사람이 읽기 쉬운 도메인 이름을 컴퓨터가 사용하는 IP 주소로 변환해 주는 인터넷의 전화번호부 시스템입니다. 그 과정은 브라우저 캐시를 먼저 확인한 뒤, 정보가 없다면 루트 서버부터 단계별 네임 서버를 거치는 재귀적 탐색을 통해 최종 IP 주소를 찾아내어 접속하는 방식입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (259,3,13,'OSI 7계층에서 역직렬화는 하위 계층에서 상위 계층으로 데이터를 전달하며 각 계층의 헤더를 제거하고 원래의 데이터 형태로 복원하는 과정을 의미합니다.
1계층(물리)에서 전기 신호를 비트 데이터로 변환하면, 2계층(데이터 링크)부터 4계층(전송)까지는 각 층의 헤더를 확인해 주소와 오류를 검증하며 캡슐을 벗겨냅니다. 이후 5~6계층을 거쳐 압축 해제나 암호 복호화 같은 표현 형식의 변환이 이루어지고, 최종적으로 7계층(응용)에서 사용자가 읽을 수 있는 데이터 객체로 복원되어 애플리케이션에 전달됩니다.

------

역직렬화는 하위 계층에서 받은 전기 신호를 상위 계층으로 올리며 각 층의 헤더를 제거(캡슐화 해제)하는 과정을 말합니다.
물리 계층의 비트 데이터를 프레임, 패킷, 세그먼트 순으로 복원하고, 최종적으로 응용 계층에서 사용자가 읽을 수 있는 데이터 객체로 변환하여 전달하는 것이 핵심입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (260,2,39,'영속성 컨텍스트는 엔티티를 영구 저장하는 가상의 환경입니다.
이점 5가지에는

- 조회 성능을 높이는 1차 캐시
- 같은 엔티티의 동일성을 보장하는 동일성 보장
- 쿼리를 모았다가 한 번에 보내는 쓰기 지연
- 수정을 자동 감지하는 변경 감지
- 연관된 객체 조회를 필요할 때까지 미루는 지연 로딩입니다.
  이를 통해 DB 접근 횟수를 줄이고 객체지향적인 코드 작성을 도와줍니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (261,2,40,'TCP는 3-way handshake로 연결을 맺어 신뢰성을 보장하지만 느립니다.
반면 UDP는 연결 절차 없이 바로 전송해서 빠르지만 신뢰성은 낮습니다.
그래서 TCP는 웹 통신에 UDP는 실시간 스트리밍에 주로 쓰입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (262,2,41,'CPU가 한 작업에서 다른 작업으로 전환하는 과정입니다.
이때 실행 중이던 작업의 상태를 PCB에 저장하고 다음 작업의 상태를 불러와 실행합니다.
이 과정에서 캐시를 비우는 등 추가 비용이 발생하는데 이를 오버헤드라고 합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (263,2,42,'유지보수하기 쉬운 객체지향 설계를 위한 5원칙입니다.

- 클래스는 하나의 책임만 가지는 단일 책임 원칙(SRP)
- 확장은 열고 수정은 닫는 개방 폐쇄 원칙(OCP)
- 자식이 부모를 대체할 수 있는 리스코프 치환 원칙(LSP)
- 인터페이스를 작게 쪼개는 인터페이스 분리 원칙(ISP)
- 구체가 아닌 추상에 의존하는 의존관계 역전 원칙(DIP)을 말합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (264,2,43,'동일성은 == 연산자(비교 연산자)로 같은 메모리 주소인지 확인하는 것입니다.
동등성은 equals()로 논리적 값이 같은지 확인하는 것입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (265,2,44,'원시타입은 실제 데이터를 스택에 직접 저장하여 속도가 빠릅니다.
반면 참조타입은 데이터는 힙에 저장하고 스택에는 그 데이터의 주소만 저장하는 방식입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (266,2,45,'세 가지 모두 문자열을 다루지만 가변성과 동기화에 차이가 있습니다.
String은 불변 객체라 변경마다 새로운 객체를 생성해 메모리 낭비가 있습니다. 
StringBuilder와 StringBuffer는 가변 객체라 직접 수정이 가능한데
StringBuffer는 동기화를 지원해 멀티스레드 환경에서 안전하고, StringBuilder는 싱글 스레드에서 속도가 더 빠릅니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (267,2,46,'Checked Exception은 컴파일 시점에 예외 처리를 강제하고
UnChecked Exception은 런타임에 발생해 처리를 강제하지 않습니다.
스프링 트랜잭션은 기본적으로 Unchecked Exception이 발생했을 때만 롤백합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (268,2,47,'- 코드를 간결하게 해주는 람다식
- 데이터를 파이프라인처럼 처리하는 Stream API
- Null 처리를 안전하게 돕는 Optional이 대표적으로 추가되었습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (269,2,48,'- TCP가 데이터 전송의 신뢰성을 보장하기 위해 사용하는 번호입니다.
- ACK 번호는 수신자가 데이터를 정상적으로 받았다는 응답이며 동시에 다음에 받을 데이터의 번호를 송신자에게 알려주는 값입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (270,2,49,'운영체제가 프로세스를 관리하고 제어하기 위해 해당 프로세스의 상태 정보를 저장해두는 자료구조 입니다.
프로세스 생성 시 고유의 PCB가 생성되어 프로세스 상태 관리와 context switching에 필수적인 고유 정보를 저장합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (271,2,50,'데이터베이스 작업의 최소 단위입니다.
여러 작업을 하나로 묶어서 모두 성공하거나 모두 실패하는 All or Nothing 방식입니다.
만약 중간에 에러가 나면 RollBack으로 원래 상태로 되돌리고
모두 성공하면 Commit으로 확정합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (272,2,51,'가장 큰 차이는 순서 보장과 중복 허용 여부입니다.
List는 데이터이 순서가 유지되고 중복이 허용됩니다.
반면 Set은 데이터의 순서가 없고 중복을 허용하지 않습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (273,2,52,'암호화는 가능하지만 복호화는 불가능한 방식입니다.
암호화에는 해시 알고리즘을 사용하고 주로 비밀번호 저장에 사용되는데 서버가 해킹당해도 원본을 알 수 없어 안전합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (274,2,53,'외부 자원을 자동으로 반납해주는 문법입니다.
try 블록이 끝나면 자동으로 close()가 호출됩니다.
그래서 파일이나 DB 연결 같은 자원 관리에 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (275,2,54,'- 강한 결합은 구체 클래스를 직접 생성해서 사용하는 방식입니다. 그래서 하나가 바뀌면 다른 코드도 모두 수정해야 합니다.

- 반면 느슨한 결합은 인터페이스에 의존하는 방식입니다. 구현체가 바뀌어도 기존 코드를 수정할 필요가 없습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (276,2,55,'직렬화는 객체를 바이트로 변환하는 것입니다.
네트워크 전송이나 파일 저장에 사용됩니다.

역직렬화는 바이트를 다시 객체로 복원하는 것입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (277,2,56,'여러 스레드가 동시에 같은 데이터를 수정할 때 발생하는 문제입니다.
데이터가 꼬이거나 예상과 다른 결과가 나올 수 있습니다.
이는 동기화 처리로 해결할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (278,2,57,'Mutable 객체는 생성 후에도 값을 변경할 수 있는 객체이고
Immutable 객체는 생성 후 값을 변경할 수 없는 객체입니다.
대표적으로 String이 있는데 불변이라 멀티스레드 환경에서 안전합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (279,2,58,'Optional을 사용하는 방법이 대표적입니다.
null 가능성이 있는 값을 Optional로 감싸서 반환하는데 이는 NullPointerException을 예방할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (280,2,59,'개발자가 직접 `new`로 생성하지 않고 스프링 컨테이너가 생성하고 관리하는 자바 객체입니다.
기본적으로 싱글톤 방식이라 메모리를 아낄 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (281,2,60,'스프링 컨테이너가 시작될 때 빈 객체를 생성하고 의존성을 주입합니다.
주입이 끝나면 초기화 과정을 거쳐 사용되고 애플리케이션이 종료될 때 소멸됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (282,2,61,'빈이 살아서 존재하는 기간이나 범위를 말합니다. 기본적으로 스프링 컨테이너에 딱 하나만 만들어지는 싱글톤 스코프,
주입될 때마다 매번 새 객체를 만들어주는 프로토타입 스코프 등이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (283,2,62,'객체의 생명주기 관리와 의존성 주입입니다.
덕분에 개발자가 `new`로 직접 생성할 필요없이 스프링이 알아서 관리해주고 코드의 결합도를 낮출 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (284,2,63,'트랜잭션이 이미 진행 중인 상태에서 다른 트랜잭션을 호출할 때 둘을 어떻게 처리할지 결정하는 옵션입니다.
대표적으로 기존 트랜잭션에 합류하는 REQUIRED, 항상 새 트랜잭션을 만드는 REQUIRES_NEW, 트랜잭션 없이 실행하는 NOT_SUPPORTED가 있습니다.
기본값은 REQUIRED입니다');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (285,2,64,'3-way는 클라이언트와 서버가 SYN, SYN-ACK, ACK를 주고 받으며 연결을 설정하는 과정이고
4-way는 FIN과 ACK를 주고 받으며 연결을 해제하는 과정입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (286,2,65,'JRE는 자바 프로그램을 실행하기 위해 필요한 환경입니다. JDK는 JRE를 포함하여 개발에 필요한 도구들까지 모두 포함한 종합 키트입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (287,2,66,'Access Token만 사용하게 되면 토큰이 탈취되었을 때 대처할 방법이 없습니다.
그래서 Access Token과 Refresh Token으로 나누어서 관리하는데
Access Token의 유효시간을 짧게 줄이고 Refresh Token으로 재발급받는 방식을 사용했습니다.
이렇게 하면 탈취당하더라도 피해를 최소화할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (288,2,67,'메신저 특성상 수많은 메시지가 오가야 하는데 </br>
HTTP를 사용하면 클라이언트가 서버에 새 메시지가 존재하는지 매번 물어봐야해서 부하가 심합니다.
웹소켓은 한 번 연결되면 양방향 통신이 계속 유지되기 때문에 서버에서 새 메시지를 바로 보낼 수 있어서 선택했습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (289,2,68,'- SSE(Server-Send Events)는 서버에서 클라이언트로만 데이터를 보내는 단방향 방식이라 알림에는 좋지만 채팅처럼
  클라이언트도 데이터를 빈번하게 보내야 하는 구조에는 맞지 않았습니다.
- Polling 방식은 주기적으로 요청을 보내므로 서버 부하가 크고 실시간성이 떨어집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (290,2,69,'생성자 주입, 필드 주입, 세터 주입 세 가지가 있습니다.
생성자 주입은 객체 생성 시점에 주입되어 불변성이 보장되고 테스트하기 쉬워서 스프링에서 권장합니다.
필드 주입은 @Autowired만 붙이면 돼서 편하지만 테스트 시 의존성 주입이 어렵습니다.
세터 주입은 선택적 의존성에 쓰이지만 외부에서 변경될 수 있어 잘 쓰지 않습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (291,2,70,'@Autowired가 붙은 필드나 생성자를 스프링이 감지하고, 컨테이너에 등록된 빈 중에서 타입이 일치하는 걸 찾아 리플렉션으로 주입합니다.
같은 타입이 여러 개면 변수명과 빈 이름을 비교해서 매칭하고, 그래도 안 되면 @Qualifier나 @Primary로 우선순위를 지정해서 해결합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (292,2,71,'클라이언트 요청을 가장 먼저 받는 프론트 컨트롤러입니다.
Handler Mapping으로 컨트롤러를 찾고 Handler Adapter가 이를 실행한 뒤 View Resolver를 거쳐 응답을 완성합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (293,2,72,'동기는 작업이 끝날때 까지 기다리는것 비동기는 작업을 맡겨두고 다른 일을 하는것입니다.
동기는 흐름이 단순하지만 대기 시간이 생기고
비동기는 처리량이 좋지만 코드가 복잡해진다는 단점이 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (294,2,73,'트랜잭션이 안전하게 처리되기 위한 4가지 속성입니다.

- 원자성은 전부 성공하거나 전부 실패
- 일관성은 트랜잭션 전후로 DB 제약조건 유지
- 격리성은 동시 트랜잭션 간 간섭 금지
- 지속성은 커밋된 데이터는 장애가 생겨도 유지되는 것입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (295,2,74,'변수, 메서드, 클래스에 붙여서 변경을 막는 키워드입니다.
변수에 붙이면 재할당 불가, 메서드에 붙이면 오버라이딩 불가, 클래스에 붙이면 상속 불가가 됩니다.
(여유있으면)주의할 점은 객체에 final을 붙일 경우 다른 객체로 갈아 끼울 수만 없을 뿐 내부의 값은 변경할 수 있습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (296,2,75,'int 같은 기본 타입을 객체로 감싼 클래스입니다.
컬렉션에 데이터를 담거나 `null`을 표현해야할 때 사용합니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (297,2,76,'토큰 안에 화면 렌더링에 필요한 사용자 정보를 담아뒀는데 httpOnly 쿠키로 저장하면 자바스크립트에서 읽을 수가 없습니다.
대신 만료 시간을 짧게 가져가는 방식으로 보완했고 리프레시 토큰은 httpOnly 쿠키로 보호했습니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (298,2,77,'순수 웹소켓은 메시지 라우팅을 직접 구현해야 하는데 STOMP를 쓰면 내장 메시지 브로커가 /topic, /queue를 구독중인 클라이언트를 관리하고 메시지를 전달해줘서 코드가 훨씬 깔끔해집니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (299,2,78,'모든 HTTP 요청을 하나의 서블릿이 통합 관리하는 패턴입니다.
공통 로직을 한 곳에서 처리해서 코드 중복을 줄이고 스프링의 DispatcherServlet이 대표적인 예입니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (300,2,79,'동작 위치가 다릅니다.
필터는 서블릿 컨테이너 레벨에서 동작해서 인코딩이나 전역 보안처리에 쓰이고
인터셉터는 스프링 컨테이너 안에서 컨트롤러 실행 전후에 동작해서 인증/인가 처리에 주로 사용됩니다.');
INSERT INTO ANSWER (ID,USER_ID,QUESTION_ID,ANSWER) values (301,2,80,'@CrossOrigin 어노테이션으로 컨트롤러 단위로 허용하거나
WebMvcConfigurer의 addCorsMappings를 오버라이딩해서 전역으로 허용 출처를 설정할 수 있습니다.');

commit;
